
/*
  Generated by Polychrony (INRIA SIGNAL/DC+ compiler) version  V4.15.8 (May 2006) 
*/
#include "vt_types.h"
#include "vt_externals.h"
#include "vt_body.h"

/*  ==> parameters and indexes */
static int i, i_965;
/*  ==> input signals     */
static logical HE;
/*  ==> output signals    */
/*  ==> local signals     */
static logical C_UP_DOWN, C_LIN_EXP;
static int PI_0, NEW_BOUND, MAX1, V, NEW_BOUND_1, VD, VU, NEW_BOUND_2, DELTA, VD_168, VU_169, CODE_CHANGE;
static logical C_SW_AUTO, NEXTAUTO, C_STOP, C_TICK;
static int DESCR;
static logical CINIT;
static int INTERM0, INTERM1, INTERM2, INTERM3, INTERM4, INTERM5;
static int cod_cond[1];
static int cod_x[6];
static logical u2, u4, u3, u1, d_stuck, d_run, d_normal, Pump_On, X0, X1, X2, X3, X4, X5, X6, Inter_Pump_On, Inter_X0, Inter_X1, Inter_X2, Inter_X3, Inter_X4, 
               Inter_X5, Inter_X6, XZX_673;
static int S_cod_u[4];
static int S_cod_y[3];
static logical fin_resolver, C_, C_C_STOP, C_NEXTAUTO, C__1276, C_1294, C_1297, C_1300, C_1303, C_1305, C_1313, C__1318, C_VD, C_1322, C_1327, C_1330, C_1335, 
               C_VD_1340, C_1342, C_1347, C_1350, C_VU, C_NEW_BOUND, C_NEW_BOUND_1371, C_VU_1374, C_NEW_BOUND_1380, C_NEW_BOUND_1386, C_fin_resolver, C_1398, 
               C_1418, C_1422, C_1430, C_1472, C_1477, C_1479, C_1481, C_1493, C_1498, C_1503, C_1508, C_1513, C_1518, C_1523, C_1528, C_1533, C_1538, C_1543, 
               C_1548, C_1553, C_1558, C_1585, C_1588, C_1594, C_Inter_Pump_Off, C_1615, C_1618, C_1621, C_1624, C_1627, C_1630, C__1642, C_1648, C_1651, C_1654
               , C_1657, C_1660, C_1663, C_1666, C_1718, C_1722, C_1734, C_1738, C_1742, C_1746, C_1750, C_1754, C_1758, XZX_1761, C_1773, C_1794, C_1797, 
               C_1800, C_1803, C_1806, C_1809, C_1812, C_1815, C_1821, C_1824, C_1830, C_1833, C_1839, C_1842, C_1848, C_1854, C_1857, C_1860, C_1863, C_1866, 
               C_Inter_X0, C_1890, C_1893, C_1896, C_1899, C_1902, C_1905, C_Inter_X1, C_Inter_X2, C_Inter_X3, C_Inter_X4, C_Inter_X5, C_Inter_X6, C_2038, 
               C_2046, C_2050, C_2054, C_2062, C_2066, C_2070, C_2074, C_2078, C_2082, C_2086;
static int _I;

EXTERN logical vt_initialize()
{
    MAX1 = 0;
    V = 1;
    NEW_BOUND = 1;
    NEXTAUTO = TRUE;
    DESCR = 0;
    CINIT = TRUE;
    cod_cond[0] = 0;
    cod_x[0] = 0;
    Pump_On = FALSE;
    X0 = FALSE;
    X1 = FALSE;
    X2 = FALSE;
    X3 = TRUE;
    X4 = FALSE;
    X5 = FALSE;
    X6 = FALSE;
    fin_resolver = TRUE;
    for (i = 0;i<4;i += 1)
        S_cod_u[i] = 0;
    for (i_965 = 0;i_965<3;i_965 += 1)
        S_cod_y[i_965] = 0;
    vt_STEP_initialize();
    return TRUE;
}

static void vt_STEP_initialize()
{
    C_LIN_EXP = FALSE;
    C_1294 = FALSE;
    C_1300 = FALSE;
    C__1318 = FALSE;
    C_NEW_BOUND = FALSE;
    C_NEW_BOUND_1380 = FALSE;
}

EXTERN logical vt_iterate()
{
    if (!r_vt_HE(&HE)) return FALSE;
    C_SW_AUTO = RAUTO();
    C_TICK = RTICK();
    C_NEXTAUTO = C_SW_AUTO || CINIT;
    if (CINIT)
        {
        GET_PACE_RHYTHM(&DESCR,&PI_0);
        }
    CODE_CHANGE = RCHANGE(DESCR);
    C_ = CODE_CHANGE != 0;
    C__1276 = C_ || CINIT;
    if (C_)
        {
        C_LIN_EXP = CODE_CHANGE == 2;
        C_1347 = FALSE;
        C_UP_DOWN = RUPDOWN(DESCR);
        C__1318 = !C_LIN_EXP;
        C_1327 = FALSE;
        if (C_LIN_EXP)
            {
            C_VD_1340 = !C_UP_DOWN;
            }
        if (C__1318)
            {
            C_VD = !C_UP_DOWN;
            }
        if (C_LIN_EXP)
            {
            C_1335 = NEW_BOUND >= 16;
            C_1342 = NEW_BOUND > 1;
            C_VU_1374 = C_UP_DOWN && C_1342;
            if (C_1335) DELTA = NEW_BOUND / 16; else DELTA = 1; 
            if (C_VD_1340)
                {
                VD_168 = NEW_BOUND + DELTA;
                C_1347 = VD_168 > 0;
                }
            C_1350 = (C_VD_1340 ? C_1347 : FALSE);
            C_NEW_BOUND_1380 = C_VU_1374 || C_1350;
            if (C_VU_1374)
                {
                VU_169 = NEW_BOUND - DELTA;
                }
            if (C_NEW_BOUND_1380)
                {
                if (C_VU_1374) NEW_BOUND_2 = VU_169; else NEW_BOUND_2 = VD_168; 
                }
            }
        if (C__1318)
            {
            C_1322 = NEW_BOUND > 1;
            C_VU = C_UP_DOWN && C_1322;
            if (C_VD)
                {
                VD = NEW_BOUND + NEW_BOUND;
                C_1327 = VD > 0;
                }
            C_1330 = (C_VD ? C_1327 : FALSE);
            C_NEW_BOUND = C_VU || C_1330;
            if (C_VU)
                {
                VU = NEW_BOUND / 2;
                }
            if (C_NEW_BOUND)
                {
                if (C_VU) NEW_BOUND_1 = VU; else NEW_BOUND_1 = VD; 
                }
            }
        }
    C_NEW_BOUND_1371 = (C__1318 ? C_NEW_BOUND : FALSE);
    C_NEW_BOUND_1386 = (C_LIN_EXP ? C_NEW_BOUND_1380 : FALSE);
    C_1398 = CINIT || C_NEW_BOUND_1386;
    C_1418 = !CINIT && C_NEW_BOUND_1386;
    C_1422 = !C_1398 && C_NEW_BOUND_1371;
    if (C_NEXTAUTO)
        {
        NEXTAUTO = !NEXTAUTO;
        RESET_PANEL(NEXTAUTO);
        }
    C_C_STOP = !NEXTAUTO;
    if (C_C_STOP)
        {
        C_STOP = RSTOP();
        if (C_STOP)
            {
            WSTOP(TRUE);
            }
        }
    if (C__1276)
        {
        if (CINIT) NEW_BOUND = PI_0; else if (C_NEW_BOUND_1386) NEW_BOUND = NEW_BOUND_2; else if (C_NEW_BOUND_1371) NEW_BOUND = NEW_BOUND_1; else ; 
        WIWRITE(DESCR,NEW_BOUND);
        C_1294 = NEW_BOUND <= 1;
        C_1300 = !(NEW_BOUND <= 1);
        }
    C_1297 = (C__1276 ? C_1294 : FALSE);
    C_1303 = (C__1276 ? C_1300 : FALSE);
    if (C__1276 || NEXTAUTO)
        {
        if (C_1297)
            MAX1 = 0;
        else if (C_1303)
            MAX1 = NEW_BOUND - 1;
        }
    if (NEXTAUTO)
        {
        C_1305 = V >= MAX1;
        if (C_1305) V = 0; else V = V + 1; 
        }
    C_1313 = (NEXTAUTO ? (V == 0) : FALSE);
    C_fin_resolver = C_TICK || C_1313;
    if (C_fin_resolver)
        {
        if (fin_resolver)
            {
            cod_cond[0] = 0;
            C_1493 = S_cod_y[0] == 1;
            C_1498 = S_cod_y[0] == -1;
            C_1503 = S_cod_y[1] == 1;
            C_1508 = S_cod_y[1] == -1;
            C_1513 = S_cod_y[2] == 1;
            C_1518 = S_cod_y[2] == -1;
            C_1523 = S_cod_u[0] == 1;
            C_1528 = S_cod_u[0] == -1;
            C_1533 = S_cod_u[1] == 1;
            C_1538 = S_cod_u[1] == -1;
            C_1543 = S_cod_u[2] == 1;
            C_1548 = S_cod_u[2] == -1;
            C_1553 = S_cod_u[3] == 1;
            C_1558 = S_cod_u[3] == -1;
            C_1734 = !C_1493 && C_1498;
            C_1738 = !C_1503 && C_1508;
            C_1742 = !C_1513 && C_1518;
            C_1746 = !C_1523 && C_1528;
            C_1750 = !C_1533 && C_1538;
            C_1754 = !C_1543 && C_1548;
            C_1758 = !C_1553 && C_1558;
            if (C_1493) d_normal = TRUE; else if (C_1498) d_normal = FALSE; else d_normal = FALSE; 
            if (C_1503) d_run = TRUE; else if (C_1508) d_run = FALSE; else d_run = FALSE; 
            if (C_1513) d_stuck = TRUE; else if (C_1518) d_stuck = FALSE; else d_stuck = FALSE; 
            if (C_1523) u1 = TRUE; else if (C_1528) u1 = FALSE; else u1 = FALSE; 
            C_1430 = u1 && d_normal;
            C_1585 = C_1430 || d_run;
            C_1588 = d_normal && !u1;
            C_1594 = C_1588 || C_1585;
            C_Inter_Pump_Off = d_stuck || C_1594;
            C_1718 = !C_1585 && C_1588;
            C_1722 = !C_1430 && d_run;
            if (C_1533) u2 = TRUE; else if (C_1538) u2 = FALSE; else u2 = FALSE; 
            if (C_1543) u3 = TRUE; else if (C_1548) u3 = FALSE; else u3 = FALSE; 
            C_1481 = !u3;
            if (C_1553) u4 = TRUE; else if (C_1558) u4 = FALSE; else u4 = FALSE; 
            C_1472 = u3 && u4;
            C_1479 = !u4;
            C__1642 = C_1479 || C_1481;
            if (C__1642)
                {
                if (C_1479) XZX_673 = u3; else XZX_673 = u4; 
                }
            XZX_1761 = (C__1642 ? XZX_673 : FALSE);
            if (C_Inter_Pump_Off)
                {
                if (C_1430) Inter_Pump_On = TRUE; else if (d_run) Inter_Pump_On = TRUE; else if (C_1588) Inter_Pump_On = FALSE; else Inter_Pump_On = FALSE; 
                }
            if (C_Inter_Pump_Off) Pump_On = Inter_Pump_On; else ; 
            Draw(Pump_On,Pump_On && u2,u2,u3,u4);
            C_1477 = !(Pump_On && u2);
            C_1615 = C_1472 && C_1477;
            C_1618 = C_1615 && X6;
            C_1621 = C_1615 && X5;
            C_1624 = C_1615 && X4;
            C_1627 = C_1615 && X3;
            C_1630 = C_1615 && X2;
            C_1648 = ((Pump_On && u2) && C_1481) && C_1479;
            C_1651 = C_1648 && X5;
            C_1654 = C_1648 && X4;
            C_1657 = C_1648 && X3;
            C_1660 = C_1648 && X2;
            C_1663 = C_1648 && X0;
            C_1666 = C_1648 && X1;
            C_1773 = (C_1477 && XZX_1761) || (C_1472 && (Pump_On && u2));
            C_1794 = C_1773 || C_1615;
            C_1797 = C_1773 && X6;
            C_1800 = C_1773 && X5;
            C_1803 = C_1773 && X4;
            C_1806 = C_1773 && X3;
            C_1809 = C_1773 && X2;
            C_1812 = C_1809 || C_1627;
            C_1815 = C_1812 || C_1663;
            C_1821 = C_1806 || C_1624;
            C_1824 = C_1821 || C_1666;
            C_1830 = C_1803 || C_1621;
            C_1833 = C_1830 || C_1660;
            C_1839 = C_1800 || C_1618;
            C_1842 = C_1839 || C_1657;
            C_1848 = C_1797 || C_1654;
            C_1854 = C_1794 || C_1648;
            C_1857 = C_1794 && X0;
            C_1860 = C_1794 && X1;
            C_1863 = C_1857 || C_1860;
            C_1866 = C_1863 || C_1630;
            C_Inter_X0 = C_1866 || C_1663;
            C_1890 = C_1854 && X6;
            C_1893 = C_1854 && X5;
            C_1896 = C_1854 && X4;
            C_1899 = C_1854 && X3;
            C_1902 = C_1854 && X2;
            C_1905 = C_1854 && X1;
            C_Inter_X1 = C_1905 || C_1815;
            C_Inter_X2 = C_1902 || C_1824;
            C_Inter_X3 = C_1899 || C_1833;
            C_Inter_X4 = C_1896 || C_1842;
            C_Inter_X5 = C_1893 || C_1848;
            C_Inter_X6 = C_1890 || C_1651;
            C_2038 = !C_1860 && C_1857;
            C_2046 = !C_1797 && C_1654;
            C_2050 = !C_1839 && C_1657;
            C_2054 = !C_1830 && C_1660;
            C_2062 = !C_1812 && C_1663;
            C_2066 = !C_1821 && C_1666;
            C_2070 = !C_1800 && C_1618;
            C_2074 = !C_1803 && C_1621;
            C_2078 = !C_1806 && C_1624;
            C_2082 = !C_1809 && C_1627;
            C_2086 = !C_1863 && C_1630;
            if (Pump_On) INTERM0 = 1; else INTERM0 = 2; 
            if (C_Inter_X0)
                {
                if (C_1860) Inter_X0 = TRUE; else if (C_1857) Inter_X0 = TRUE; else if (C_1630) Inter_X0 = TRUE; else Inter_X0 = FALSE; 
                }
            if (C_Inter_X0) X0 = Inter_X0; else ; 
            if (X0) INTERM1 = 1; else INTERM1 = 2; 
            if (C_Inter_X1)
                {
                if (C_1809) Inter_X1 = TRUE; else if (C_1627) Inter_X1 = TRUE; else if (C_1663) Inter_X1 = TRUE; else Inter_X1 = FALSE; 
                }
            if (C_Inter_X1) X1 = Inter_X1; else ; 
            if (X1) INTERM2 = 1; else INTERM2 = 2; 
            if (C_Inter_X2)
                {
                if (C_1806) Inter_X2 = TRUE; else if (C_1624) Inter_X2 = TRUE; else if (C_1666) Inter_X2 = TRUE; else Inter_X2 = FALSE; 
                }
            if (C_Inter_X2) X2 = Inter_X2; else ; 
            if (X2) INTERM5 = 1; else INTERM5 = 2; 
            if (C_Inter_X3)
                {
                if (C_1803) Inter_X3 = TRUE; else if (C_1621) Inter_X3 = TRUE; else if (C_1660) Inter_X3 = TRUE; else Inter_X3 = FALSE; 
                }
            if (C_Inter_X3) X3 = Inter_X3; else ; 
            if (C_Inter_X4)
                {
                if (C_1800) Inter_X4 = TRUE; else if (C_1618) Inter_X4 = TRUE; else if (C_1657) Inter_X4 = TRUE; else Inter_X4 = FALSE; 
                }
            if (C_Inter_X4) X4 = Inter_X4; else ; 
            if (C_Inter_X5)
                {
                if (C_1797) Inter_X5 = TRUE; else if (C_1654) Inter_X5 = TRUE; else Inter_X5 = FALSE; 
                }
            if (C_Inter_X5) X5 = Inter_X5; else ; 
            if (X5) INTERM3 = 1; else INTERM3 = 2; 
            if (C_Inter_X6)
                {
                if (C_1651) Inter_X6 = TRUE; else Inter_X6 = FALSE; 
                }
            if (C_Inter_X6) X6 = Inter_X6; else ; 
            Draw_State(X0,X1,X2,X3,X4,X5,X6,Pump_On && u2);
            if (X6) INTERM4 = 1; else INTERM4 = 2; 
            cod_x[0] = INTERM0;
            cod_x[1] = INTERM1;
            cod_x[2] = INTERM2;
            cod_x[3] = INTERM3;
            cod_x[4] = INTERM4;
            cod_x[5] = INTERM5;
            }
        resolver(cod_cond,cod_x,S_cod_u,S_cod_y,&fin_resolver);
        }
    vt_STEP_finalize();
    return TRUE;
}

EXTERN logical vt_STEP_finalize()
{
    CINIT = FALSE;
    vt_STEP_initialize();
    return TRUE;
}

