/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LiaisonResolveur */

#ifndef _Included_LiaisonResolveur
#define _Included_LiaisonResolveur
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LiaisonResolveur
 * Method:    n_chargement
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LiaisonResolveur_n_1chargement
  (JNIEnv *, jobject, jstring);

/*
 * Class:     LiaisonResolveur
 * Method:    n_raz
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LiaisonResolveur_n_1raz
  (JNIEnv *, jobject);

/*
 * Class:     LiaisonResolveur
 * Method:    n_set_config
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_LiaisonResolveur_n_1set_1config
  (JNIEnv *, jobject, jint);

/*
 * Class:     LiaisonResolveur
 * Method:    n_set_etats
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_LiaisonResolveur_n_1set_1etats
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     LiaisonResolveur
 * Method:    n_set_conditions
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_LiaisonResolveur_n_1set_1conditions
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     LiaisonResolveur
 * Method:    n_set_une_condition
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_LiaisonResolveur_n_1set_1une_1condition
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     LiaisonResolveur
 * Method:    n_set_mesures
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_LiaisonResolveur_n_1set_1mesures
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     LiaisonResolveur
 * Method:    n_set_une_incontrolable
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_LiaisonResolveur_n_1set_1une_1incontrolable
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     LiaisonResolveur
 * Method:    n_set_inconnue
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_LiaisonResolveur_n_1set_1inconnue
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     LiaisonResolveur
 * Method:    n_init_resolution
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LiaisonResolveur_n_1init_1resolution
  (JNIEnv *, jobject);

/*
 * Class:     LiaisonResolveur
 * Method:    n_init_resolution_par_defaut
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LiaisonResolveur_n_1init_1resolution_1par_1defaut
  (JNIEnv *, jobject);

/*
 * Class:     LiaisonResolveur
 * Method:    n_get_valperm
 * Signature: ([II)Z
 */
JNIEXPORT jboolean JNICALL Java_LiaisonResolveur_n_1get_1valperm
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     LiaisonResolveur
 * Method:    n_get_solution
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_LiaisonResolveur_n_1get_1solution
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
