/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LiaisonPacemaker */

#ifndef _Included_LiaisonPacemaker
#define _Included_LiaisonPacemaker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LiaisonPacemaker
 * Method:    n_inter_pace_up_p
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LiaisonPacemaker_n_1inter_1pace_1up_1p
  (JNIEnv *, jobject);

/*
 * Class:     LiaisonPacemaker
 * Method:    n_inter_pace_down_p
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LiaisonPacemaker_n_1inter_1pace_1down_1p
  (JNIEnv *, jobject);

/*
 * Class:     LiaisonPacemaker
 * Method:    n_inter_pace_up_m
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LiaisonPacemaker_n_1inter_1pace_1up_1m
  (JNIEnv *, jobject);

/*
 * Class:     LiaisonPacemaker
 * Method:    n_inter_pace_down_m
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LiaisonPacemaker_n_1inter_1pace_1down_1m
  (JNIEnv *, jobject);

/*
 * Class:     LiaisonPacemaker
 * Method:    n_inter_auto
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LiaisonPacemaker_n_1inter_1auto
  (JNIEnv *, jobject);

/*
 * Class:     LiaisonPacemaker
 * Method:    n_inter_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LiaisonPacemaker_n_1inter_1stop
  (JNIEnv *, jobject);

/*
 * Class:     LiaisonPacemaker
 * Method:    n_inter_tick
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LiaisonPacemaker_n_1inter_1tick
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
