
/*
  Generated by Polychrony (INRIA SIGNAL/DC+ compiler) version  V4.15.8 (May 2006) 
*/
#include "vt_types.h"
#include "vt_externals.h"
#include "vt_body.h"

/*  ==> parameters and indexes */
static int i, i_633;
/*  ==> input signals     */
static logical HE;
/*  ==> output signals    */
/*  ==> local signals     */
static logical C_UP_DOWN, C_LIN_EXP;
static int PI_0, NEW_BOUND;
static logical CINIT;
static int DESCR;
static logical C_TICK, C_SW_AUTO, NEXTAUTO, C_STOP;
static int CODE_CHANGE, MAX1, V, NEW_BOUND_1, DELTA, VD, VU, NEW_BOUND_2, VD_318, VU_319, INTERM0, INTERM1;
static int cod_cond[1];
static int cod_x[2];
static logical Mult, Incr, CC, New_B1, New_B2, C2, C1, CCa, C2a, C1a, Cout1;
static int S_cod_u[1], S_cod_y[1];
static logical fin_resolver, C_C_STOP, C_, C_842, C_850, C__855, C_857, C_VD, C_864, C_869, C_872, C_VD_877, C_879, C_884, C_887, C_OLD_BOUND, C_NEXTAUTO, C_VU,
               C_NEW_BOUND, C_NEW_BOUND_932, C_935, C_VU_938, C_NEW_BOUND_944, C_NEW_BOUND_950, C_fin_resolver, C_969, C_972, C_989, C_992, C_995, C_998, C_1022
               , C_1027, C_1032, C_1037, C_C1, C_1061, C_1065, C_1069;
static int _I;

EXTERN logical vt_initialize()
{
    CINIT = TRUE;
    DESCR = 0;
    NEXTAUTO = TRUE;
    MAX1 = 0;
    V = 1;
    NEW_BOUND = 1;
    cod_cond[0] = 0;
    cod_x[0] = 0;
    New_B2 = FALSE;
    New_B1 = FALSE;
    fin_resolver = TRUE;
    for (i = 0;i<1;i += 1)
        S_cod_u[i] = 0;
    for (i_633 = 0;i_633<1;i_633 += 1)
        S_cod_y[i_633] = 0;
    vt_STEP_initialize();
    return TRUE;
}

static void vt_STEP_initialize()
{
    C_LIN_EXP = FALSE;
    C__855 = FALSE;
    C_NEW_BOUND = FALSE;
    C_NEW_BOUND_944 = FALSE;
    C_989 = FALSE;
    C_995 = FALSE;
}

EXTERN logical vt_iterate()
{
    if (!r_vt_HE(&HE)) return FALSE;
    C_TICK = RTICK();
    C_SW_AUTO = RAUTO();
    C_NEXTAUTO = CINIT || C_SW_AUTO;
    if (CINIT)
        {
        GET_PACE_RHYTHM(&DESCR,&PI_0);
        }
    CODE_CHANGE = RCHANGE(DESCR);
    C_ = CODE_CHANGE != 0;
    C_OLD_BOUND = CINIT || C_;
    if (C_)
        {
        C_LIN_EXP = CODE_CHANGE == 2;
        C_869 = FALSE;
        C_UP_DOWN = RUPDOWN(DESCR);
        C__855 = !C_LIN_EXP;
        C_884 = FALSE;
        if (C_LIN_EXP)
            {
            C_VD = !C_UP_DOWN;
            }
        if (C__855)
            {
            C_VD_877 = !C_UP_DOWN;
            }
        if (C_LIN_EXP)
            {
            C_857 = NEW_BOUND >= 16;
            C_864 = NEW_BOUND > 1;
            C_VU = C_UP_DOWN && C_864;
            if (C_857) DELTA = NEW_BOUND / 16; else DELTA = 1; 
            if (C_VD)
                {
                VD = NEW_BOUND + DELTA;
                C_869 = VD > 0;
                }
            C_872 = (C_VD ? C_869 : FALSE);
            C_NEW_BOUND = C_VU || C_872;
            if (C_VU)
                {
                VU = NEW_BOUND - DELTA;
                }
            if (C_NEW_BOUND)
                {
                if (C_VU) NEW_BOUND_1 = VU; else NEW_BOUND_1 = VD; 
                }
            }
        if (C__855)
            {
            C_879 = NEW_BOUND > 1;
            C_VU_938 = C_UP_DOWN && C_879;
            if (C_VD_877)
                {
                VD_318 = NEW_BOUND + NEW_BOUND;
                C_884 = VD_318 > 0;
                }
            C_887 = (C_VD_877 ? C_884 : FALSE);
            C_NEW_BOUND_944 = C_VU_938 || C_887;
            if (C_VU_938)
                {
                VU_319 = NEW_BOUND / 2;
                }
            if (C_NEW_BOUND_944)
                {
                if (C_VU_938) NEW_BOUND_2 = VU_319; else NEW_BOUND_2 = VD_318; 
                }
            }
        }
    C_NEW_BOUND_932 = (C_LIN_EXP ? C_NEW_BOUND : FALSE);
    C_935 = CINIT || C_NEW_BOUND_932;
    C_NEW_BOUND_950 = (C__855 ? C_NEW_BOUND_944 : FALSE);
    C_969 = !C_935 && C_NEW_BOUND_950;
    C_972 = !CINIT && C_NEW_BOUND_932;
    if (C_OLD_BOUND)
        {
        if (CINIT) NEW_BOUND = PI_0; else if (C_NEW_BOUND_932) NEW_BOUND = NEW_BOUND_1; else if (C_NEW_BOUND_950) NEW_BOUND = NEW_BOUND_2; else ; 
        C_989 = NEW_BOUND <= 1;
        C_995 = !(NEW_BOUND <= 1);
        }
    C_992 = (C_OLD_BOUND ? C_989 : FALSE);
    C_998 = (C_OLD_BOUND ? C_995 : FALSE);
    if (C_NEXTAUTO)
        {
        NEXTAUTO = !NEXTAUTO;
        }
    C_C_STOP = !NEXTAUTO;
    if (C_C_STOP)
        {
        C_STOP = RSTOP();
        if (C_STOP)
            {
            WSTOP(TRUE);
            }
        }
    if (NEXTAUTO || C_OLD_BOUND)
        {
        if (C_992)
            MAX1 = 0;
        else if (C_998)
            MAX1 = NEW_BOUND - 1;
        }
    if (NEXTAUTO)
        {
        C_842 = V >= MAX1;
        if (C_842) V = 0; else V = V + 1; 
        }
    C_850 = (NEXTAUTO ? (V == 0) : FALSE);
    C_fin_resolver = C_TICK || C_850;
    if (C_fin_resolver)
        {
        if (fin_resolver)
            {
            cod_cond[0] = 0;
            C_1022 = S_cod_y[0] == 1;
            C_1027 = S_cod_y[0] == -1;
            C_1032 = S_cod_u[0] == 1;
            C_1037 = S_cod_u[0] == -1;
            C_1065 = !C_1022 && C_1027;
            C_1069 = !C_1032 && C_1037;
            if (C_1022) Mult = TRUE; else if (C_1027) Mult = FALSE; else Mult = FALSE; 
            if (C_1032) Incr = TRUE; else if (C_1037) Incr = FALSE; else Incr = FALSE; 
            C_C1 = Incr || Mult;
            C_1061 = !Incr && Mult;
            if (Incr) C1a = !New_B1; else C1a = New_B1; 
            Cout1 = New_B1 && !C1a;
            if (Cout1) C2a = !New_B2; else C2a = New_B2; 
            CCa = New_B2 && !C2a;
            if (Incr) CC = CCa; else if (Mult) CC = New_B2; else CC = FALSE; 
            if (C_C1)
                {
                if (Incr) C2 = C2a; else C2 = New_B1; 
                if (Incr) C1 = C1a; else C1 = FALSE; 
                }
            if (C_C1) New_B1 = C1; else ; 
            if (C_C1) New_B2 = C2; else ; 
            Draw(CC,New_B1,New_B2);
            if (New_B1) INTERM0 = 1; else INTERM0 = 2; 
            if (New_B2) INTERM1 = 1; else INTERM1 = 2; 
            cod_x[0] = INTERM0;
            cod_x[1] = INTERM1;
            }
        resolver(cod_cond,cod_x,S_cod_u,S_cod_y,&fin_resolver);
        }
    vt_STEP_finalize();
    return TRUE;
}

EXTERN logical vt_STEP_finalize()
{
    CINIT = FALSE;
    vt_STEP_initialize();
    return TRUE;
}

