
/*
  Generated by Polychrony (INRIA SIGNAL/DC+ compiler) version  V4.15.8
*/
#include "vt_types.h"
#include "vt_externals.h"
#include "vt_body.h"

/*  ==> parameters and indexes */
static int i, i_2737;
/*  ==> input signals     */
static logical HE;
/*  ==> output signals    */
/*  ==> local signals     */
static logical C_UP_DOWN, C_LIN_EXP;
static int PI_0, NEW_BOUND, MAX1, ZV, V, OLD_BOUND, NEW_BOUND_1, VD, VU, NEW_BOUND_2, DELTA_177, VD_178, VU_179, CODE_CHANGE;
static logical C_SW_AUTO, ZAUTO, NEXTAUTO, C_STOP, C_TICK;
static int DESCR;
static logical CINIT;
static int INTERM0, INTERM1, INTERM2, INTERM3, INTERM4, INTERM5, INTERM6, INTERM7, INTERM8, INTERM9, INTERM10, INTERM11, INTERM12, INTERM13, INTERM14, INTERM15,
           INTERM16, INTERM17, INTERM18, INTERM19, INTERM20, INTERM21, INTERM22, INTERM23, INTERM24, INTERM25, INTERM26, INTERM27, INTERM28, INTERM29;
static int cod_cond[1];
static int cod_x[30];
static logical NEXT_WST56, NEXT_WST55, NEXT_WST54, NEXT_WST53, NEXT_WST52, NEXT_WST51, NEXT_WST42, NEXT_WST41, NEXT_WST34, NEXT_WST33, NEXT_WST32, NEXT_WST31, 
               NEXT_WST24, NEXT_WST23, NEXT_WST22, NEXT_WST21, NEXT_WST14, NEXT_WST13, NEXT_WST12, NEXT_WST11, NEXT_AGV58, NEXT_AGV57, NEXT_AGV56, NEXT_AGV55, 
               NEXT_AGV54, NEXT_AGV53, NEXT_AGV52, NEXT_AGV51, NEXT_AGV410, NEXT_AGV49, NEXT_AGV48, NEXT_AGV47, NEXT_AGV46, NEXT_AGV45, NEXT_AGV44, NEXT_AGV43, 
               NEXT_AGV42, NEXT_AGV41, NEXT_AGV36, NEXT_AGV35, NEXT_AGV34, NEXT_AGV33, NEXT_AGV32, NEXT_AGV31, NEXT_AGV212, NEXT_AGV211, NEXT_AGV210, NEXT_AGV29
               , NEXT_AGV28, NEXT_AGV27, NEXT_AGV26, NEXT_AGV25, NEXT_AGV24, NEXT_AGV23, NEXT_AGV22, NEXT_AGV21, NEXT_AGV16, NEXT_AGV15, NEXT_AGV14, NEXT_AGV13,
               NEXT_AGV12, NEXT_AGV11, C10, C9, C8, C7, C6, C5, C4, C3, C2, C1, CURRENT_WST11, CURRENT_WST12, CURRENT_WST13, CURRENT_WST14, CURRENT_WST21, 
               CURRENT_WST22, CURRENT_WST23, CURRENT_WST24, CURRENT_WST31, CURRENT_WST32, CURRENT_WST33, CURRENT_WST34, CURRENT_WST41, CURRENT_WST42, 
               CURRENT_WST51, CURRENT_WST52, CURRENT_WST53, CURRENT_WST54, CURRENT_WST55, CURRENT_WST56, CURRENT_AGV11, CURRENT_AGV12, CURRENT_AGV13, 
               CURRENT_AGV14, CURRENT_AGV15, CURRENT_AGV16, CURRENT_AGV21, CURRENT_AGV22, CURRENT_AGV23, CURRENT_AGV24, CURRENT_AGV25, CURRENT_AGV26, 
               CURRENT_AGV27, CURRENT_AGV28, CURRENT_AGV29, CURRENT_AGV210, CURRENT_AGV211, CURRENT_AGV212, CURRENT_AGV31, CURRENT_AGV32, CURRENT_AGV33, 
               CURRENT_AGV34, CURRENT_AGV35, CURRENT_AGV36, CURRENT_AGV41, CURRENT_AGV42, CURRENT_AGV43, CURRENT_AGV44, CURRENT_AGV45, CURRENT_AGV46, 
               CURRENT_AGV47, CURRENT_AGV48, CURRENT_AGV49, CURRENT_AGV410, CURRENT_AGV51, CURRENT_AGV52, CURRENT_AGV53, CURRENT_AGV54, CURRENT_AGV55, 
               CURRENT_AGV56, CURRENT_AGV57, CURRENT_AGV58;
static int Pos_1, Pos_2, Pos_3, Pos_4, Pos_5, Pos_6;
static int Pos_AGV1[7];
static logical INTER_NEXT_AGV11, INTER_NEXT_AGV12, INTER_NEXT_AGV13, INTER_NEXT_AGV14, INTER_NEXT_AGV15, INTER_NEXT_AGV16;
static int Pos_AGV2[13];
static logical INTER_NEXT_AGV21, INTER_NEXT_AGV22, INTER_NEXT_AGV23, INTER_NEXT_AGV24, INTER_NEXT_AGV25, INTER_NEXT_AGV26, INTER_NEXT_AGV27, INTER_NEXT_AGV28, 
               INTER_NEXT_AGV29, INTER_NEXT_AGV210, INTER_NEXT_AGV211, INTER_NEXT_AGV212;
static int Pos_1_1017, Pos_2_1018, Pos_3_1019, Pos_4_1020, Pos_5_1021, Pos_6_1022, Pos_7, Pos_8, Pos_9, Pos_10, Pos_11, Pos_12, Pos_1_1250, Pos_2_1251, 
           Pos_3_1252, Pos_4_1253, Pos_5_1254, Pos_6_1255;
static int Pos_AGV3[7];
static logical INTER_NEXT_AGV31, INTER_NEXT_AGV32, INTER_NEXT_AGV33, INTER_NEXT_AGV34, INTER_NEXT_AGV35, INTER_NEXT_AGV36;
static int Pos_1_1422, Pos_2_1423, Pos_3_1424, Pos_4_1425, Pos_5_1426, Pos_6_1427, Pos_7_1428, Pos_8_1429, Pos_9_1430, Pos_10_1431;
static int Pos_AGV4[11];
static logical INTER_NEXT_AGV41, INTER_NEXT_AGV42, INTER_NEXT_AGV43, INTER_NEXT_AGV44, INTER_NEXT_AGV45, INTER_NEXT_AGV46, INTER_NEXT_AGV47, INTER_NEXT_AGV48, 
               INTER_NEXT_AGV49, INTER_NEXT_AGV410;
static int Pos_1_1642, Pos_2_1643, Pos_3_1644, Pos_4_1645, Pos_5_1646, Pos_6_1647, Pos_7_1648, Pos_8_1649;
static int Pos_AGV5[9];
static logical INTER_NEXT_AGV51, INTER_NEXT_AGV52, INTER_NEXT_AGV53, INTER_NEXT_AGV54, INTER_NEXT_AGV55, INTER_NEXT_AGV56, INTER_NEXT_AGV57, INTER_NEXT_AGV58;
static int Pos_1_1810, Pos_2_1811, Pos_3_1812, Pos_4_1813;
static int Pos_WST1[5];
static logical INTER_NEXT_WST11, INTER_NEXT_WST12, INTER_NEXT_WST13, INTER_NEXT_WST14;
static int Pos_1_1914, Pos_2_1915, Pos_3_1916, Pos_4_1917;
static int Pos_WST2[5];
static logical INTER_NEXT_WST21, INTER_NEXT_WST22, INTER_NEXT_WST23, INTER_NEXT_WST24;
static int Pos_1_2020, Pos_2_2021, Pos_3_2022, Pos_4_2023;
static int Pos_WST3[5];
static logical INTER_NEXT_WST31, INTER_NEXT_WST32, INTER_NEXT_WST33, INTER_NEXT_WST34;
static int Pos_1_2110, Pos_2_2111;
static int Pos_WST4[3];
static logical INTER_NEXT_WST41, INTER_NEXT_WST42;
static int Pos_1_2199, Pos_2_2200, Pos_3_2201, Pos_4_2202, Pos_5_2203, Pos_6_2204;
static int Pos_WST5[7];
static logical INTER_NEXT_WST51, INTER_NEXT_WST52, INTER_NEXT_WST53, INTER_NEXT_WST54, INTER_NEXT_WST55, INTER_NEXT_WST56, z_b, b, fin_resolver;
static int IS_cod_u;
static int TS_cod_u[2][10];
static int IS_cod_y;
static int TS_cod_y[2][1];
static int IZ_S_cod_u;
static logical C_, C_C_STOP, C_NEXTAUTO, C__3040, C_3058, C_3061, C_3064, C_3067, C_3069, C_3077, C__3082, C_VD, C_3091, C_3094, C_3099, C_VD_3104, C_3111, 
               C_3114, C_VU, C_NEW_BOUND, C_NEW_BOUND_3135, C_VU_3138, C_NEW_BOUND_3144, C_NEW_BOUND_3150, C_Z_S_cod_y, C_3162, C_3182, C_3186, C_3621, C_3626, 
               C_3631, C_3636, C_3641, C_3646, C_3651, C_3656, C_3661, C_3666, C_3671, C_3676, C_3681, C_3686, C_3691, C_3696, C_3701, C_3706, C_3711, C_3716, 
               C_3773, C_INTER_NEXT_AGV11, C_3785, C_INTER_NEXT_AGV12, C_INTER_NEXT_AGV13, C_3812, C_INTER_NEXT_AGV14, C_3824, C_INTER_NEXT_AGV15, 
               C_INTER_NEXT_AGV16, C_3851, C_INTER_NEXT_AGV21, C_3863, C_INTER_NEXT_AGV22, C_INTER_NEXT_AGV23, C_INTER_NEXT_AGV24, C_INTER_NEXT_AGV25, 
               C_INTER_NEXT_AGV26, C_3899, C_INTER_NEXT_AGV27, C_3911, C_INTER_NEXT_AGV28, C_INTER_NEXT_AGV29, C_INTER_NEXT_AGV210, C_INTER_NEXT_AGV211, 
               C_INTER_NEXT_AGV212, C_3947, C_INTER_NEXT_AGV31, C_3959, C_INTER_NEXT_AGV32, C_INTER_NEXT_AGV33, C_3986, C_INTER_NEXT_AGV34, C_INTER_NEXT_WST21, 
               C_4013, C_INTER_NEXT_AGV35, C_INTER_NEXT_AGV36, C_4040, C_INTER_NEXT_AGV41, C_4052, C_INTER_NEXT_AGV42, C_INTER_NEXT_AGV43, C_INTER_NEXT_AGV44, 
               C_INTER_NEXT_AGV45, C_4091, C_INTER_NEXT_AGV46, C_INTER_NEXT_WST31, C_4112, C_INTER_NEXT_AGV47, C_INTER_NEXT_AGV48, C_INTER_NEXT_AGV49, 
               C_INTER_NEXT_AGV410, C_4157, C_INTER_NEXT_AGV51, C_INTER_NEXT_WST53, C_INTER_NEXT_WST51, C_4187, C_INTER_NEXT_AGV52, C_INTER_NEXT_AGV53, 
               C_INTER_NEXT_AGV54, C_4217, C_INTER_NEXT_AGV55, C_INTER_NEXT_AGV56, C_4238, C_INTER_NEXT_AGV57, C_INTER_NEXT_AGV58, C_INTER_NEXT_WST12, 
               C_INTER_NEXT_WST14, C_INTER_NEXT_WST22, C_INTER_NEXT_WST23, C_INTER_NEXT_WST24, C_INTER_NEXT_WST32, C_INTER_NEXT_WST33, C_INTER_NEXT_WST34, 
               C_INTER_NEXT_WST42, C_4334, C_INTER_NEXT_WST54, C_INTER_NEXT_WST52, C_INTER_NEXT_WST55, C_INTER_NEXT_WST56, C_4818, C_4822, C_4826, C_4830, 
               C_4834, C_4838, C_4842, C_4846, C_4850, C_4854;
static int _I;

EXTERN logical vt_initialize()
{
    MAX1 = 0;
    ZV = 1;
    OLD_BOUND = 1;
    ZAUTO = TRUE;
    NEXTAUTO = TRUE;
    DESCR = 0;
    CINIT = TRUE;
    cod_cond[0] = 0;
    cod_x[0] = 0;
    CURRENT_WST11 = TRUE;
    CURRENT_WST12 = FALSE;
    CURRENT_WST13 = TRUE;
    CURRENT_WST14 = FALSE;
    CURRENT_WST21 = TRUE;
    CURRENT_WST22 = FALSE;
    CURRENT_WST23 = FALSE;
    CURRENT_WST24 = FALSE;
    CURRENT_WST31 = TRUE;
    CURRENT_WST32 = FALSE;
    CURRENT_WST33 = FALSE;
    CURRENT_WST34 = FALSE;
    CURRENT_WST41 = TRUE;
    CURRENT_WST42 = FALSE;
    CURRENT_WST51 = TRUE;
    CURRENT_WST52 = FALSE;
    CURRENT_WST53 = TRUE;
    CURRENT_WST54 = FALSE;
    CURRENT_WST55 = FALSE;
    CURRENT_WST56 = FALSE;
    CURRENT_AGV11 = TRUE;
    CURRENT_AGV12 = FALSE;
    CURRENT_AGV13 = FALSE;
    CURRENT_AGV14 = FALSE;
    CURRENT_AGV15 = FALSE;
    CURRENT_AGV16 = FALSE;
    CURRENT_AGV21 = TRUE;
    CURRENT_AGV22 = FALSE;
    CURRENT_AGV23 = FALSE;
    CURRENT_AGV24 = FALSE;
    CURRENT_AGV25 = FALSE;
    CURRENT_AGV26 = FALSE;
    CURRENT_AGV27 = FALSE;
    CURRENT_AGV28 = FALSE;
    CURRENT_AGV29 = FALSE;
    CURRENT_AGV210 = FALSE;
    CURRENT_AGV211 = FALSE;
    CURRENT_AGV212 = FALSE;
    CURRENT_AGV31 = TRUE;
    CURRENT_AGV32 = FALSE;
    CURRENT_AGV33 = FALSE;
    CURRENT_AGV34 = FALSE;
    CURRENT_AGV35 = FALSE;
    CURRENT_AGV36 = FALSE;
    CURRENT_AGV41 = TRUE;
    CURRENT_AGV42 = FALSE;
    CURRENT_AGV43 = FALSE;
    CURRENT_AGV44 = FALSE;
    CURRENT_AGV45 = FALSE;
    CURRENT_AGV46 = FALSE;
    CURRENT_AGV47 = FALSE;
    CURRENT_AGV48 = FALSE;
    CURRENT_AGV49 = FALSE;
    CURRENT_AGV410 = FALSE;
    CURRENT_AGV51 = TRUE;
    CURRENT_AGV52 = FALSE;
    CURRENT_AGV53 = FALSE;
    CURRENT_AGV54 = FALSE;
    CURRENT_AGV55 = FALSE;
    CURRENT_AGV56 = FALSE;
    CURRENT_AGV57 = FALSE;
    CURRENT_AGV58 = FALSE;
    z_b = TRUE;
    IS_cod_u = 0;
    IS_cod_y = 0;
    IZ_S_cod_u = 0;
    for (i = 0;i<10;i += 1)
        TS_cod_u[IZ_S_cod_u][i] = 0;
    IZ_S_cod_u = 0;
    vt_STEP_initialize();
    return TRUE;
}

static void vt_STEP_initialize()
{
    C_LIN_EXP = FALSE;
    C_3058 = FALSE;
    C_3064 = FALSE;
    C__3082 = FALSE;
    C_NEW_BOUND = FALSE;
    C_NEW_BOUND_3144 = FALSE;
}

EXTERN logical vt_iterate()
{
    if (!r_vt_HE(&HE)) return FALSE;
    C_SW_AUTO = RAUTO();
    C_TICK = RTICK();
    C_NEXTAUTO = C_SW_AUTO || CINIT;
    if (CINIT)
        {
        GET_PACE_RHYTHM(&DESCR,&PI_0);
        }
    CODE_CHANGE = RCHANGE(DESCR);
    C_ = CODE_CHANGE != 0;
    C__3040 = C_ || CINIT;
    if (C_)
        {
        C_LIN_EXP = CODE_CHANGE == 2;
        C_3111 = FALSE;
        C_UP_DOWN = RUPDOWN(DESCR);
        C__3082 = !C_LIN_EXP;
        C_3091 = FALSE;
        if (C_LIN_EXP)
            {
            C_VD_3104 = !C_UP_DOWN;
            }
        if (C__3082)
            {
            C_VD = !C_UP_DOWN;
            }
        if (C_LIN_EXP)
            {
            C_3099 = OLD_BOUND >= 16;
            C_VU_3138 = C_UP_DOWN && (OLD_BOUND > 1);
            if (C_3099) DELTA_177 = OLD_BOUND / 16; else DELTA_177 = 1; 
            if (C_VD_3104)
                {
                VD_178 = OLD_BOUND + DELTA_177;
                C_3111 = VD_178 > 0;
                }
            C_3114 = (C_VD_3104 ? C_3111 : FALSE);
            C_NEW_BOUND_3144 = C_VU_3138 || C_3114;
            if (C_VU_3138)
                {
                VU_179 = OLD_BOUND - DELTA_177;
                }
            if (C_NEW_BOUND_3144)
                {
                if (C_VU_3138) NEW_BOUND_2 = VU_179; else NEW_BOUND_2 = VD_178; 
                }
            }
        if (C__3082)
            {
            C_VU = C_UP_DOWN && (OLD_BOUND > 1);
            if (C_VD)
                {
                VD = OLD_BOUND + OLD_BOUND;
                C_3091 = VD > 0;
                }
            C_3094 = (C_VD ? C_3091 : FALSE);
            C_NEW_BOUND = C_VU || C_3094;
            if (C_VU)
                {
                VU = OLD_BOUND / 2;
                }
            if (C_NEW_BOUND)
                {
                if (C_VU) NEW_BOUND_1 = VU; else NEW_BOUND_1 = VD; 
                }
            }
        }
    C_NEW_BOUND_3135 = (C__3082 ? C_NEW_BOUND : FALSE);
    C_NEW_BOUND_3150 = (C_LIN_EXP ? C_NEW_BOUND_3144 : FALSE);
    C_3162 = CINIT || C_NEW_BOUND_3150;
    C_3182 = !CINIT && C_NEW_BOUND_3150;
    C_3186 = !C_3162 && C_NEW_BOUND_3135;
    if (C_NEXTAUTO)
        {
        NEXTAUTO = !ZAUTO;
        RESET_PANEL(NEXTAUTO);
        }
    C_C_STOP = !NEXTAUTO;
    if (C_C_STOP)
        {
        C_STOP = RSTOP();
        if (C_STOP)
            {
            WSTOP(TRUE);
            }
        }
    if (C__3040)
        {
        if (CINIT) NEW_BOUND = PI_0; else if (C_NEW_BOUND_3150) NEW_BOUND = NEW_BOUND_2; else if (C_NEW_BOUND_3135) NEW_BOUND = NEW_BOUND_1; else NEW_BOUND = 
        OLD_BOUND; 
        WIWRITE(DESCR,NEW_BOUND);
        C_3058 = NEW_BOUND <= 1;
        C_3064 = !(NEW_BOUND <= 1);
        }
    C_3061 = (C__3040 ? C_3058 : FALSE);
    C_3067 = (C__3040 ? C_3064 : FALSE);
    if (C__3040 || NEXTAUTO)
        {
        if (C_3061)
            MAX1 = 0;
        else if (C_3067)
            MAX1 = NEW_BOUND - 1;
        }
    if (NEXTAUTO)
        {
        C_3069 = ZV >= MAX1;
        if (C_3069) V = 0; else V = ZV + 1; 
        }
    C_3077 = (NEXTAUTO ? (V == 0) : FALSE);
    C_Z_S_cod_y = C_TICK || C_3077;
    if (C_Z_S_cod_y)
        {
        if (z_b)
            {
            cod_cond[0] = 0;
            C_3621 = TS_cod_u[IZ_S_cod_u][0] == 1;
            C_3626 = TS_cod_u[IZ_S_cod_u][0] == -1;
            C_3631 = TS_cod_u[IZ_S_cod_u][1] == 1;
            C_3636 = TS_cod_u[IZ_S_cod_u][1] == -1;
            C_3641 = TS_cod_u[IZ_S_cod_u][2] == 1;
            C_3646 = TS_cod_u[IZ_S_cod_u][2] == -1;
            C_3651 = TS_cod_u[IZ_S_cod_u][3] == 1;
            C_3656 = TS_cod_u[IZ_S_cod_u][3] == -1;
            C_3661 = TS_cod_u[IZ_S_cod_u][4] == 1;
            C_3666 = TS_cod_u[IZ_S_cod_u][4] == -1;
            C_3671 = TS_cod_u[IZ_S_cod_u][5] == 1;
            C_3676 = TS_cod_u[IZ_S_cod_u][5] == -1;
            C_3681 = TS_cod_u[IZ_S_cod_u][6] == 1;
            C_3686 = TS_cod_u[IZ_S_cod_u][6] == -1;
            C_3691 = TS_cod_u[IZ_S_cod_u][7] == 1;
            C_3696 = TS_cod_u[IZ_S_cod_u][7] == -1;
            C_3701 = TS_cod_u[IZ_S_cod_u][8] == 1;
            C_3706 = TS_cod_u[IZ_S_cod_u][8] == -1;
            C_3711 = TS_cod_u[IZ_S_cod_u][9] == 1;
            C_3716 = TS_cod_u[IZ_S_cod_u][9] == -1;
            C_3773 = CURRENT_WST11 && CURRENT_AGV11;
            C_INTER_NEXT_AGV11 = C_3773 || CURRENT_AGV16;
            C_3812 = CURRENT_WST21 && CURRENT_AGV14;
            C_INTER_NEXT_AGV14 = C_3812 || CURRENT_AGV13;
            C_3851 = CURRENT_WST13 && CURRENT_AGV21;
            C_INTER_NEXT_AGV21 = C_3851 || CURRENT_AGV212;
            C_INTER_NEXT_AGV24 = CURRENT_AGV23 || CURRENT_AGV24;
            C_INTER_NEXT_AGV25 = CURRENT_AGV24 || CURRENT_AGV25;
            C_INTER_NEXT_AGV26 = CURRENT_AGV25 || CURRENT_AGV26;
            C_3899 = CURRENT_WST31 && CURRENT_AGV27;
            C_INTER_NEXT_AGV27 = C_3899 || CURRENT_AGV26;
            C_INTER_NEXT_AGV210 = CURRENT_AGV29 || CURRENT_AGV210;
            C_INTER_NEXT_AGV211 = CURRENT_AGV210 || CURRENT_AGV211;
            C_INTER_NEXT_AGV212 = CURRENT_AGV212 || CURRENT_AGV211;
            C_3947 = CURRENT_WST51 && CURRENT_AGV31;
            C_INTER_NEXT_AGV31 = C_3947 || CURRENT_AGV36;
            C_3986 = CURRENT_WST24 && CURRENT_AGV34;
            C_INTER_NEXT_AGV34 = C_3986 || CURRENT_AGV33;
            C_INTER_NEXT_WST21 = C_3986 || C_3812;
            C_4040 = CURRENT_WST53 && CURRENT_AGV41;
            C_INTER_NEXT_AGV41 = C_4040 || CURRENT_AGV410;
            C_INTER_NEXT_AGV44 = CURRENT_AGV43 || CURRENT_AGV44;
            C_INTER_NEXT_AGV45 = CURRENT_AGV44 || CURRENT_AGV45;
            C_4091 = CURRENT_WST34 && CURRENT_AGV46;
            C_INTER_NEXT_AGV46 = C_4091 || CURRENT_AGV45;
            C_INTER_NEXT_WST31 = C_4091 || C_3899;
            C_INTER_NEXT_AGV49 = CURRENT_AGV48 || CURRENT_AGV49;
            C_INTER_NEXT_AGV410 = CURRENT_AGV410 || CURRENT_AGV49;
            C_4157 = CURRENT_WST56 && CURRENT_AGV51;
            C_INTER_NEXT_AGV51 = C_4157 || CURRENT_AGV58;
            C_INTER_NEXT_WST53 = C_4157 || C_4040;
            C_INTER_NEXT_WST51 = C_4157 || C_3947;
            C_INTER_NEXT_AGV54 = CURRENT_AGV53 || CURRENT_AGV54;
            C_4217 = CURRENT_WST42 && CURRENT_AGV55;
            C_INTER_NEXT_AGV55 = C_4217 || CURRENT_AGV54;
            C_INTER_NEXT_AGV56 = CURRENT_AGV56 || C_4217;
            C_INTER_NEXT_WST12 = CURRENT_WST12 || C_3773;
            C_INTER_NEXT_WST14 = CURRENT_WST14 || C_3851;
            C_INTER_NEXT_WST22 = CURRENT_WST22 || C_3812;
            C_INTER_NEXT_WST23 = CURRENT_WST22 || CURRENT_WST23;
            C_INTER_NEXT_WST24 = CURRENT_WST23 || C_3986;
            C_INTER_NEXT_WST32 = CURRENT_WST32 || C_3899;
            C_INTER_NEXT_WST33 = CURRENT_WST32 || CURRENT_WST33;
            C_INTER_NEXT_WST34 = CURRENT_WST33 || C_4091;
            C_INTER_NEXT_WST42 = CURRENT_WST41 || C_4217;
            C_4334 = CURRENT_WST54 && CURRENT_WST52;
            C_INTER_NEXT_WST54 = C_4334 || C_4040;
            C_INTER_NEXT_WST52 = C_4334 || C_3947;
            C_INTER_NEXT_WST55 = CURRENT_WST55 || C_4334;
            C_INTER_NEXT_WST56 = CURRENT_WST55 || C_4157;
            C_4818 = !C_3621 && C_3626;
            C_4822 = !C_3631 && C_3636;
            C_4826 = !C_3641 && C_3646;
            C_4830 = !C_3651 && C_3656;
            C_4834 = !C_3661 && C_3666;
            C_4838 = !C_3671 && C_3676;
            C_4842 = !C_3681 && C_3686;
            C_4846 = !C_3691 && C_3696;
            C_4850 = !C_3701 && C_3706;
            C_4854 = !C_3711 && C_3716;
            if (C_3621) C1 = TRUE; else if (C_3626) C1 = FALSE; else C1 = FALSE; 
            C_3785 = CURRENT_AGV12 && C1;
            C_INTER_NEXT_AGV12 = C_3785 || C_3773;
            C_INTER_NEXT_AGV13 = CURRENT_AGV13 || C_3785;
            if (C_3631) C2 = TRUE; else if (C_3636) C2 = FALSE; else C2 = FALSE; 
            C_3824 = CURRENT_AGV15 && C2;
            C_INTER_NEXT_AGV15 = C_3824 || C_3812;
            C_INTER_NEXT_AGV16 = C_3824 || CURRENT_AGV16;
            if (C_3641) C3 = TRUE; else if (C_3646) C3 = FALSE; else C3 = FALSE; 
            C_3863 = CURRENT_AGV22 && C3;
            C_INTER_NEXT_AGV22 = C_3863 || C_3851;
            C_INTER_NEXT_AGV23 = CURRENT_AGV23 || C_3863;
            if (C_3651) C4 = TRUE; else if (C_3656) C4 = FALSE; else C4 = FALSE; 
            C_3911 = CURRENT_AGV28 && C4;
            C_INTER_NEXT_AGV28 = C_3911 || C_3899;
            C_INTER_NEXT_AGV29 = CURRENT_AGV29 || C_3911;
            if (C_3661) C5 = TRUE; else if (C_3666) C5 = FALSE; else C5 = FALSE; 
            C_3959 = CURRENT_AGV32 && C5;
            C_INTER_NEXT_AGV32 = C_3959 || C_3947;
            C_INTER_NEXT_AGV33 = CURRENT_AGV33 || C_3959;
            if (C_3671) C6 = TRUE; else if (C_3676) C6 = FALSE; else C6 = FALSE; 
            C_4013 = CURRENT_AGV35 && C6;
            C_INTER_NEXT_AGV35 = C_4013 || C_3986;
            C_INTER_NEXT_AGV36 = C_4013 || CURRENT_AGV36;
            if (C_3681) C7 = TRUE; else if (C_3686) C7 = FALSE; else C7 = FALSE; 
            C_4052 = CURRENT_AGV42 && C7;
            C_INTER_NEXT_AGV42 = C_4052 || C_4040;
            C_INTER_NEXT_AGV43 = CURRENT_AGV43 || C_4052;
            if (C_3691) C8 = TRUE; else if (C_3696) C8 = FALSE; else C8 = FALSE; 
            C_4112 = CURRENT_AGV47 && C8;
            C_INTER_NEXT_AGV47 = C_4112 || C_4091;
            C_INTER_NEXT_AGV48 = CURRENT_AGV48 || C_4112;
            if (C_3701) C9 = TRUE; else if (C_3706) C9 = FALSE; else C9 = FALSE; 
            C_4187 = CURRENT_AGV52 && C9;
            C_INTER_NEXT_AGV52 = C_4187 || C_4157;
            C_INTER_NEXT_AGV53 = CURRENT_AGV53 || C_4187;
            if (C_3711) C10 = TRUE; else if (C_3716) C10 = FALSE; else C10 = FALSE; 
            C_4238 = CURRENT_AGV57 && C10;
            C_INTER_NEXT_AGV57 = C_4238 || CURRENT_AGV56;
            C_INTER_NEXT_AGV58 = C_4238 || CURRENT_AGV58;
            if (C_INTER_NEXT_WST12)
                {
                if (CURRENT_WST12) INTER_NEXT_WST11 = TRUE; else INTER_NEXT_WST11 = FALSE; 
                if (C_3773) INTER_NEXT_WST12 = TRUE; else INTER_NEXT_WST12 = FALSE; 
                }
            if (C_INTER_NEXT_WST12) NEXT_WST12 = INTER_NEXT_WST12; else NEXT_WST12 = CURRENT_WST12; 
            if (C_INTER_NEXT_WST12) NEXT_WST11 = INTER_NEXT_WST11; else NEXT_WST11 = CURRENT_WST11; 
            if (NEXT_WST11) Pos_1_1810 = 1; else Pos_1_1810 = 0; 
            if (NEXT_WST12) Pos_2_1811 = 1; else Pos_2_1811 = 0; 
            if (C_INTER_NEXT_WST14)
                {
                if (CURRENT_WST14) INTER_NEXT_WST13 = TRUE; else INTER_NEXT_WST13 = FALSE; 
                if (C_3851) INTER_NEXT_WST14 = TRUE; else INTER_NEXT_WST14 = FALSE; 
                }
            if (C_INTER_NEXT_WST14) NEXT_WST14 = INTER_NEXT_WST14; else NEXT_WST14 = CURRENT_WST14; 
            if (C_INTER_NEXT_WST14) NEXT_WST13 = INTER_NEXT_WST13; else NEXT_WST13 = CURRENT_WST13; 
            if (NEXT_WST13) Pos_3_1812 = 1; else Pos_3_1812 = 0; 
            if (NEXT_WST14) Pos_4_1813 = 1; else Pos_4_1813 = 0; 
            Pos_WST1[0] = 1;
            Pos_WST1[1] = Pos_1_1810;
            Pos_WST1[2] = Pos_2_1811;
            Pos_WST1[3] = Pos_3_1812;
            Pos_WST1[4] = Pos_4_1813;
            dessine_chariot_wst1(Pos_WST1);
            if (C_INTER_NEXT_WST42)
                {
                if (C_4217) INTER_NEXT_WST41 = TRUE; else INTER_NEXT_WST41 = FALSE; 
                if (CURRENT_WST41) INTER_NEXT_WST42 = TRUE; else INTER_NEXT_WST42 = FALSE; 
                }
            if (C_INTER_NEXT_WST42) NEXT_WST42 = INTER_NEXT_WST42; else NEXT_WST42 = CURRENT_WST42; 
            if (C_INTER_NEXT_WST42) NEXT_WST41 = INTER_NEXT_WST41; else NEXT_WST41 = CURRENT_WST41; 
            if (NEXT_WST41) Pos_1_2110 = 1; else Pos_1_2110 = 0; 
            if (NEXT_WST42) Pos_2_2111 = 1; else Pos_2_2111 = 0; 
            Pos_WST4[0] = 1;
            Pos_WST4[1] = Pos_1_2110;
            Pos_WST4[2] = Pos_2_2111;
            dessine_chariot_wst4(Pos_WST4);
            if (C_INTER_NEXT_AGV11)
                {
                if (CURRENT_AGV16) INTER_NEXT_AGV11 = TRUE; else INTER_NEXT_AGV11 = FALSE; 
                }
            if (C_INTER_NEXT_AGV11) NEXT_AGV11 = INTER_NEXT_AGV11; else NEXT_AGV11 = CURRENT_AGV11; 
            if (NEXT_AGV11) Pos_1 = 1; else Pos_1 = 0; 
            if (C_INTER_NEXT_AGV12)
                {
                if (C_3773) INTER_NEXT_AGV12 = TRUE; else INTER_NEXT_AGV12 = FALSE; 
                }
            if (C_INTER_NEXT_AGV12) NEXT_AGV12 = INTER_NEXT_AGV12; else NEXT_AGV12 = CURRENT_AGV12; 
            if (NEXT_AGV12) INTERM6 = 1; else INTERM6 = 2; 
            if (NEXT_AGV12) Pos_2 = 1; else Pos_2 = 0; 
            if (C_INTER_NEXT_AGV13)
                {
                if (C_3785) INTER_NEXT_AGV13 = TRUE; else INTER_NEXT_AGV13 = FALSE; 
                }
            if (C_INTER_NEXT_AGV13) NEXT_AGV13 = INTER_NEXT_AGV13; else NEXT_AGV13 = CURRENT_AGV13; 
            if (NEXT_AGV13) INTERM7 = 1; else INTERM7 = 2; 
            if (NEXT_AGV13) Pos_3 = 1; else Pos_3 = 0; 
            if (C_INTER_NEXT_AGV14)
                {
                if (CURRENT_AGV13) INTER_NEXT_AGV14 = TRUE; else INTER_NEXT_AGV14 = FALSE; 
                }
            if (C_INTER_NEXT_AGV14) NEXT_AGV14 = INTER_NEXT_AGV14; else NEXT_AGV14 = CURRENT_AGV14; 
            if (NEXT_AGV14) Pos_4 = 1; else Pos_4 = 0; 
            if (C_INTER_NEXT_AGV15)
                {
                if (C_3812) INTER_NEXT_AGV15 = TRUE; else INTER_NEXT_AGV15 = FALSE; 
                }
            if (C_INTER_NEXT_AGV15) NEXT_AGV15 = INTER_NEXT_AGV15; else NEXT_AGV15 = CURRENT_AGV15; 
            if (NEXT_AGV15) INTERM8 = 1; else INTERM8 = 2; 
            if (NEXT_AGV15) Pos_5 = 1; else Pos_5 = 0; 
            if (C_INTER_NEXT_AGV16)
                {
                if (C_3824) INTER_NEXT_AGV16 = TRUE; else INTER_NEXT_AGV16 = FALSE; 
                }
            if (C_INTER_NEXT_AGV16) NEXT_AGV16 = INTER_NEXT_AGV16; else NEXT_AGV16 = CURRENT_AGV16; 
            if (NEXT_AGV16) INTERM9 = 1; else INTERM9 = 2; 
            if (NEXT_AGV16) Pos_6 = 1; else Pos_6 = 0; 
            Pos_AGV1[0] = 1;
            Pos_AGV1[1] = Pos_1;
            Pos_AGV1[2] = Pos_2;
            Pos_AGV1[3] = Pos_3;
            Pos_AGV1[4] = Pos_4;
            Pos_AGV1[5] = Pos_5;
            Pos_AGV1[6] = Pos_6;
            dessine_chariot_agv1(Pos_AGV1);
            if (C_INTER_NEXT_AGV21)
                {
                if (CURRENT_AGV212) INTER_NEXT_AGV21 = TRUE; else INTER_NEXT_AGV21 = FALSE; 
                }
            if (C_INTER_NEXT_AGV21) NEXT_AGV21 = INTER_NEXT_AGV21; else NEXT_AGV21 = CURRENT_AGV21; 
            if (NEXT_AGV21) Pos_1_1017 = 1; else Pos_1_1017 = 0; 
            if (C_INTER_NEXT_AGV22)
                {
                if (C_3851) INTER_NEXT_AGV22 = TRUE; else INTER_NEXT_AGV22 = FALSE; 
                }
            if (C_INTER_NEXT_AGV22) NEXT_AGV22 = INTER_NEXT_AGV22; else NEXT_AGV22 = CURRENT_AGV22; 
            if (NEXT_AGV22) INTERM10 = 1; else INTERM10 = 2; 
            if (NEXT_AGV22) Pos_2_1018 = 1; else Pos_2_1018 = 0; 
            if (C_INTER_NEXT_AGV23)
                {
                if (C_3863) INTER_NEXT_AGV23 = TRUE; else INTER_NEXT_AGV23 = FALSE; 
                }
            if (C_INTER_NEXT_AGV23) NEXT_AGV23 = INTER_NEXT_AGV23; else NEXT_AGV23 = CURRENT_AGV23; 
            if (NEXT_AGV23) INTERM11 = 1; else INTERM11 = 2; 
            if (NEXT_AGV23) Pos_3_1019 = 1; else Pos_3_1019 = 0; 
            if (C_INTER_NEXT_AGV24)
                {
                if (CURRENT_AGV23) INTER_NEXT_AGV24 = TRUE; else INTER_NEXT_AGV24 = FALSE; 
                }
            if (C_INTER_NEXT_AGV24) NEXT_AGV24 = INTER_NEXT_AGV24; else NEXT_AGV24 = CURRENT_AGV24; 
            if (NEXT_AGV24) INTERM0 = 1; else INTERM0 = 2; 
            if (NEXT_AGV24) Pos_4_1020 = 1; else Pos_4_1020 = 0; 
            if (C_INTER_NEXT_AGV25)
                {
                if (CURRENT_AGV24) INTER_NEXT_AGV25 = TRUE; else INTER_NEXT_AGV25 = FALSE; 
                }
            if (C_INTER_NEXT_AGV25) NEXT_AGV25 = INTER_NEXT_AGV25; else NEXT_AGV25 = CURRENT_AGV25; 
            if (NEXT_AGV25) INTERM1 = 1; else INTERM1 = 2; 
            if (NEXT_AGV25) Pos_5_1021 = 1; else Pos_5_1021 = 0; 
            if (C_INTER_NEXT_AGV26)
                {
                if (CURRENT_AGV25) INTER_NEXT_AGV26 = TRUE; else INTER_NEXT_AGV26 = FALSE; 
                }
            if (C_INTER_NEXT_AGV26) NEXT_AGV26 = INTER_NEXT_AGV26; else NEXT_AGV26 = CURRENT_AGV26; 
            if (NEXT_AGV26) INTERM12 = 1; else INTERM12 = 2; 
            if (NEXT_AGV26) Pos_6_1022 = 1; else Pos_6_1022 = 0; 
            if (C_INTER_NEXT_AGV27)
                {
                if (CURRENT_AGV26) INTER_NEXT_AGV27 = TRUE; else INTER_NEXT_AGV27 = FALSE; 
                }
            if (C_INTER_NEXT_AGV27) NEXT_AGV27 = INTER_NEXT_AGV27; else NEXT_AGV27 = CURRENT_AGV27; 
            if (NEXT_AGV27) Pos_7 = 1; else Pos_7 = 0; 
            if (C_INTER_NEXT_AGV28)
                {
                if (C_3899) INTER_NEXT_AGV28 = TRUE; else INTER_NEXT_AGV28 = FALSE; 
                }
            if (C_INTER_NEXT_AGV28) NEXT_AGV28 = INTER_NEXT_AGV28; else NEXT_AGV28 = CURRENT_AGV28; 
            if (NEXT_AGV28) INTERM13 = 1; else INTERM13 = 2; 
            if (NEXT_AGV28) Pos_8 = 1; else Pos_8 = 0; 
            if (C_INTER_NEXT_AGV29)
                {
                if (C_3911) INTER_NEXT_AGV29 = TRUE; else INTER_NEXT_AGV29 = FALSE; 
                }
            if (C_INTER_NEXT_AGV29) NEXT_AGV29 = INTER_NEXT_AGV29; else NEXT_AGV29 = CURRENT_AGV29; 
            if (NEXT_AGV29) INTERM2 = 1; else INTERM2 = 2; 
            if (NEXT_AGV29) Pos_9 = 1; else Pos_9 = 0; 
            if (C_INTER_NEXT_AGV210)
                {
                if (CURRENT_AGV29) INTER_NEXT_AGV210 = TRUE; else INTER_NEXT_AGV210 = FALSE; 
                }
            if (C_INTER_NEXT_AGV210) NEXT_AGV210 = INTER_NEXT_AGV210; else NEXT_AGV210 = CURRENT_AGV210; 
            if (NEXT_AGV210) INTERM14 = 1; else INTERM14 = 2; 
            if (NEXT_AGV210) Pos_10 = 1; else Pos_10 = 0; 
            if (C_INTER_NEXT_AGV211)
                {
                if (CURRENT_AGV210) INTER_NEXT_AGV211 = TRUE; else INTER_NEXT_AGV211 = FALSE; 
                }
            if (C_INTER_NEXT_AGV211) NEXT_AGV211 = INTER_NEXT_AGV211; else NEXT_AGV211 = CURRENT_AGV211; 
            if (NEXT_AGV211) INTERM15 = 1; else INTERM15 = 2; 
            if (NEXT_AGV211) Pos_11 = 1; else Pos_11 = 0; 
            if (C_INTER_NEXT_AGV212)
                {
                if (CURRENT_AGV211) INTER_NEXT_AGV212 = TRUE; else INTER_NEXT_AGV212 = FALSE; 
                }
            if (C_INTER_NEXT_AGV212) NEXT_AGV212 = INTER_NEXT_AGV212; else NEXT_AGV212 = CURRENT_AGV212; 
            if (NEXT_AGV212) INTERM16 = 1; else INTERM16 = 2; 
            if (NEXT_AGV212) Pos_12 = 1; else Pos_12 = 0; 
            Pos_AGV2[0] = 1;
            Pos_AGV2[1] = Pos_1_1017;
            Pos_AGV2[2] = Pos_2_1018;
            Pos_AGV2[3] = Pos_3_1019;
            Pos_AGV2[4] = Pos_4_1020;
            Pos_AGV2[5] = Pos_5_1021;
            Pos_AGV2[6] = Pos_6_1022;
            Pos_AGV2[7] = Pos_7;
            Pos_AGV2[8] = Pos_8;
            Pos_AGV2[9] = Pos_9;
            Pos_AGV2[10] = Pos_10;
            Pos_AGV2[11] = Pos_11;
            Pos_AGV2[12] = Pos_12;
            dessine_chariot_agv2(Pos_AGV2);
            if (C_INTER_NEXT_AGV31)
                {
                if (CURRENT_AGV36) INTER_NEXT_AGV31 = TRUE; else INTER_NEXT_AGV31 = FALSE; 
                }
            if (C_INTER_NEXT_AGV31) NEXT_AGV31 = INTER_NEXT_AGV31; else NEXT_AGV31 = CURRENT_AGV31; 
            if (NEXT_AGV31) Pos_1_1250 = 1; else Pos_1_1250 = 0; 
            if (C_INTER_NEXT_AGV32)
                {
                if (C_3947) INTER_NEXT_AGV32 = TRUE; else INTER_NEXT_AGV32 = FALSE; 
                }
            if (C_INTER_NEXT_AGV32) NEXT_AGV32 = INTER_NEXT_AGV32; else NEXT_AGV32 = CURRENT_AGV32; 
            if (NEXT_AGV32) INTERM17 = 1; else INTERM17 = 2; 
            if (NEXT_AGV32) Pos_2_1251 = 1; else Pos_2_1251 = 0; 
            if (C_INTER_NEXT_AGV33)
                {
                if (C_3959) INTER_NEXT_AGV33 = TRUE; else INTER_NEXT_AGV33 = FALSE; 
                }
            if (C_INTER_NEXT_AGV33) NEXT_AGV33 = INTER_NEXT_AGV33; else NEXT_AGV33 = CURRENT_AGV33; 
            if (NEXT_AGV33) INTERM18 = 1; else INTERM18 = 2; 
            if (NEXT_AGV33) Pos_3_1252 = 1; else Pos_3_1252 = 0; 
            if (C_INTER_NEXT_AGV34)
                {
                if (CURRENT_AGV33) INTER_NEXT_AGV34 = TRUE; else INTER_NEXT_AGV34 = FALSE; 
                }
            if (C_INTER_NEXT_AGV34) NEXT_AGV34 = INTER_NEXT_AGV34; else NEXT_AGV34 = CURRENT_AGV34; 
            if (NEXT_AGV34) Pos_4_1253 = 1; else Pos_4_1253 = 0; 
            if (C_INTER_NEXT_WST21)
                {
                if (C_3986) INTER_NEXT_WST21 = TRUE; else INTER_NEXT_WST21 = FALSE; 
                }
            if (C_INTER_NEXT_WST21) NEXT_WST21 = INTER_NEXT_WST21; else NEXT_WST21 = CURRENT_WST21; 
            if (NEXT_WST21) Pos_1_1914 = 1; else Pos_1_1914 = 0; 
            if (C_INTER_NEXT_AGV35)
                {
                if (C_3986) INTER_NEXT_AGV35 = TRUE; else INTER_NEXT_AGV35 = FALSE; 
                }
            if (C_INTER_NEXT_AGV35) NEXT_AGV35 = INTER_NEXT_AGV35; else NEXT_AGV35 = CURRENT_AGV35; 
            if (NEXT_AGV35) INTERM19 = 1; else INTERM19 = 2; 
            if (NEXT_AGV35) Pos_5_1254 = 1; else Pos_5_1254 = 0; 
            if (C_INTER_NEXT_AGV36)
                {
                if (C_4013) INTER_NEXT_AGV36 = TRUE; else INTER_NEXT_AGV36 = FALSE; 
                }
            if (C_INTER_NEXT_AGV36) NEXT_AGV36 = INTER_NEXT_AGV36; else NEXT_AGV36 = CURRENT_AGV36; 
            if (NEXT_AGV36) INTERM20 = 1; else INTERM20 = 2; 
            if (NEXT_AGV36) Pos_6_1255 = 1; else Pos_6_1255 = 0; 
            Pos_AGV3[0] = 1;
            Pos_AGV3[1] = Pos_1_1250;
            Pos_AGV3[2] = Pos_2_1251;
            Pos_AGV3[3] = Pos_3_1252;
            Pos_AGV3[4] = Pos_4_1253;
            Pos_AGV3[5] = Pos_5_1254;
            Pos_AGV3[6] = Pos_6_1255;
            dessine_chariot_agv3(Pos_AGV3);
            if (C_INTER_NEXT_AGV41)
                {
                if (CURRENT_AGV410) INTER_NEXT_AGV41 = TRUE; else INTER_NEXT_AGV41 = FALSE; 
                }
            if (C_INTER_NEXT_AGV41) NEXT_AGV41 = INTER_NEXT_AGV41; else NEXT_AGV41 = CURRENT_AGV41; 
            if (NEXT_AGV41) Pos_1_1422 = 1; else Pos_1_1422 = 0; 
            if (C_INTER_NEXT_AGV42)
                {
                if (C_4040) INTER_NEXT_AGV42 = TRUE; else INTER_NEXT_AGV42 = FALSE; 
                }
            if (C_INTER_NEXT_AGV42) NEXT_AGV42 = INTER_NEXT_AGV42; else NEXT_AGV42 = CURRENT_AGV42; 
            if (NEXT_AGV42) INTERM21 = 1; else INTERM21 = 2; 
            if (NEXT_AGV42) Pos_2_1423 = 1; else Pos_2_1423 = 0; 
            if (C_INTER_NEXT_AGV43)
                {
                if (C_4052) INTER_NEXT_AGV43 = TRUE; else INTER_NEXT_AGV43 = FALSE; 
                }
            if (C_INTER_NEXT_AGV43) NEXT_AGV43 = INTER_NEXT_AGV43; else NEXT_AGV43 = CURRENT_AGV43; 
            if (NEXT_AGV43) INTERM3 = 1; else INTERM3 = 2; 
            if (NEXT_AGV43) Pos_3_1424 = 1; else Pos_3_1424 = 0; 
            if (C_INTER_NEXT_AGV44)
                {
                if (CURRENT_AGV43) INTER_NEXT_AGV44 = TRUE; else INTER_NEXT_AGV44 = FALSE; 
                }
            if (C_INTER_NEXT_AGV44) NEXT_AGV44 = INTER_NEXT_AGV44; else NEXT_AGV44 = CURRENT_AGV44; 
            if (NEXT_AGV44) INTERM22 = 1; else INTERM22 = 2; 
            if (NEXT_AGV44) Pos_4_1425 = 1; else Pos_4_1425 = 0; 
            if (C_INTER_NEXT_AGV45)
                {
                if (CURRENT_AGV44) INTER_NEXT_AGV45 = TRUE; else INTER_NEXT_AGV45 = FALSE; 
                }
            if (C_INTER_NEXT_AGV45) NEXT_AGV45 = INTER_NEXT_AGV45; else NEXT_AGV45 = CURRENT_AGV45; 
            if (NEXT_AGV45) INTERM23 = 1; else INTERM23 = 2; 
            if (NEXT_AGV45) Pos_5_1426 = 1; else Pos_5_1426 = 0; 
            if (C_INTER_NEXT_AGV46)
                {
                if (CURRENT_AGV45) INTER_NEXT_AGV46 = TRUE; else INTER_NEXT_AGV46 = FALSE; 
                }
            if (C_INTER_NEXT_AGV46) NEXT_AGV46 = INTER_NEXT_AGV46; else NEXT_AGV46 = CURRENT_AGV46; 
            if (NEXT_AGV46) Pos_6_1427 = 1; else Pos_6_1427 = 0; 
            if (C_INTER_NEXT_WST31)
                {
                if (C_4091) INTER_NEXT_WST31 = TRUE; else INTER_NEXT_WST31 = FALSE; 
                }
            if (C_INTER_NEXT_WST31) NEXT_WST31 = INTER_NEXT_WST31; else NEXT_WST31 = CURRENT_WST31; 
            if (NEXT_WST31) Pos_1_2020 = 1; else Pos_1_2020 = 0; 
            if (C_INTER_NEXT_AGV47)
                {
                if (C_4091) INTER_NEXT_AGV47 = TRUE; else INTER_NEXT_AGV47 = FALSE; 
                }
            if (C_INTER_NEXT_AGV47) NEXT_AGV47 = INTER_NEXT_AGV47; else NEXT_AGV47 = CURRENT_AGV47; 
            if (NEXT_AGV47) INTERM24 = 1; else INTERM24 = 2; 
            if (NEXT_AGV47) Pos_7_1428 = 1; else Pos_7_1428 = 0; 
            if (C_INTER_NEXT_AGV48)
                {
                if (C_4112) INTER_NEXT_AGV48 = TRUE; else INTER_NEXT_AGV48 = FALSE; 
                }
            if (C_INTER_NEXT_AGV48) NEXT_AGV48 = INTER_NEXT_AGV48; else NEXT_AGV48 = CURRENT_AGV48; 
            if (NEXT_AGV48) INTERM4 = 1; else INTERM4 = 2; 
            if (NEXT_AGV48) Pos_8_1429 = 1; else Pos_8_1429 = 0; 
            if (C_INTER_NEXT_AGV49)
                {
                if (CURRENT_AGV48) INTER_NEXT_AGV49 = TRUE; else INTER_NEXT_AGV49 = FALSE; 
                }
            if (C_INTER_NEXT_AGV49) NEXT_AGV49 = INTER_NEXT_AGV49; else NEXT_AGV49 = CURRENT_AGV49; 
            if (NEXT_AGV49) INTERM5 = 1; else INTERM5 = 2; 
            if (NEXT_AGV49) Pos_9_1430 = 1; else Pos_9_1430 = 0; 
            if (C_INTER_NEXT_AGV410)
                {
                if (CURRENT_AGV49) INTER_NEXT_AGV410 = TRUE; else INTER_NEXT_AGV410 = FALSE; 
                }
            if (C_INTER_NEXT_AGV410) NEXT_AGV410 = INTER_NEXT_AGV410; else NEXT_AGV410 = CURRENT_AGV410; 
            if (NEXT_AGV410) INTERM25 = 1; else INTERM25 = 2; 
            if (NEXT_AGV410) Pos_10_1431 = 1; else Pos_10_1431 = 0; 
            Pos_AGV4[0] = 1;
            Pos_AGV4[1] = Pos_1_1422;
            Pos_AGV4[2] = Pos_2_1423;
            Pos_AGV4[3] = Pos_3_1424;
            Pos_AGV4[4] = Pos_4_1425;
            Pos_AGV4[5] = Pos_5_1426;
            Pos_AGV4[6] = Pos_6_1427;
            Pos_AGV4[7] = Pos_7_1428;
            Pos_AGV4[8] = Pos_8_1429;
            Pos_AGV4[9] = Pos_9_1430;
            Pos_AGV4[10] = Pos_10_1431;
            dessine_chariot_agv4(Pos_AGV4);
            if (C_INTER_NEXT_AGV51)
                {
                if (CURRENT_AGV58) INTER_NEXT_AGV51 = TRUE; else INTER_NEXT_AGV51 = FALSE; 
                }
            if (C_INTER_NEXT_AGV51) NEXT_AGV51 = INTER_NEXT_AGV51; else NEXT_AGV51 = CURRENT_AGV51; 
            if (NEXT_AGV51) Pos_1_1642 = 1; else Pos_1_1642 = 0; 
            if (C_INTER_NEXT_WST53)
                {
                if (C_4157) INTER_NEXT_WST53 = TRUE; else INTER_NEXT_WST53 = FALSE; 
                }
            if (C_INTER_NEXT_WST53) NEXT_WST53 = INTER_NEXT_WST53; else NEXT_WST53 = CURRENT_WST53; 
            if (NEXT_WST53) Pos_3_2201 = 1; else Pos_3_2201 = 0; 
            if (C_INTER_NEXT_WST51)
                {
                if (C_4157) INTER_NEXT_WST51 = TRUE; else INTER_NEXT_WST51 = FALSE; 
                }
            if (C_INTER_NEXT_WST51) NEXT_WST51 = INTER_NEXT_WST51; else NEXT_WST51 = CURRENT_WST51; 
            if (NEXT_WST51) Pos_1_2199 = 1; else Pos_1_2199 = 0; 
            if (C_INTER_NEXT_AGV52)
                {
                if (C_4157) INTER_NEXT_AGV52 = TRUE; else INTER_NEXT_AGV52 = FALSE; 
                }
            if (C_INTER_NEXT_AGV52) NEXT_AGV52 = INTER_NEXT_AGV52; else NEXT_AGV52 = CURRENT_AGV52; 
            if (NEXT_AGV52) INTERM26 = 1; else INTERM26 = 2; 
            if (NEXT_AGV52) Pos_2_1643 = 1; else Pos_2_1643 = 0; 
            if (C_INTER_NEXT_AGV53)
                {
                if (C_4187) INTER_NEXT_AGV53 = TRUE; else INTER_NEXT_AGV53 = FALSE; 
                }
            if (C_INTER_NEXT_AGV53) NEXT_AGV53 = INTER_NEXT_AGV53; else NEXT_AGV53 = CURRENT_AGV53; 
            if (NEXT_AGV53) INTERM27 = 1; else INTERM27 = 2; 
            if (NEXT_AGV53) Pos_3_1644 = 1; else Pos_3_1644 = 0; 
            if (C_INTER_NEXT_AGV54)
                {
                if (CURRENT_AGV53) INTER_NEXT_AGV54 = TRUE; else INTER_NEXT_AGV54 = FALSE; 
                }
            if (C_INTER_NEXT_AGV54) NEXT_AGV54 = INTER_NEXT_AGV54; else NEXT_AGV54 = CURRENT_AGV54; 
            if (NEXT_AGV54) Pos_4_1645 = 1; else Pos_4_1645 = 0; 
            if (C_INTER_NEXT_AGV55)
                {
                if (CURRENT_AGV54) INTER_NEXT_AGV55 = TRUE; else INTER_NEXT_AGV55 = FALSE; 
                }
            if (C_INTER_NEXT_AGV55) NEXT_AGV55 = INTER_NEXT_AGV55; else NEXT_AGV55 = CURRENT_AGV55; 
            if (NEXT_AGV55) Pos_5_1646 = 1; else Pos_5_1646 = 0; 
            if (C_INTER_NEXT_AGV56)
                {
                if (C_4217) INTER_NEXT_AGV56 = TRUE; else INTER_NEXT_AGV56 = FALSE; 
                }
            if (C_INTER_NEXT_AGV56) NEXT_AGV56 = INTER_NEXT_AGV56; else NEXT_AGV56 = CURRENT_AGV56; 
            if (NEXT_AGV56) Pos_6_1647 = 1; else Pos_6_1647 = 0; 
            if (C_INTER_NEXT_AGV57)
                {
                if (CURRENT_AGV56) INTER_NEXT_AGV57 = TRUE; else INTER_NEXT_AGV57 = FALSE; 
                }
            if (C_INTER_NEXT_AGV57) NEXT_AGV57 = INTER_NEXT_AGV57; else NEXT_AGV57 = CURRENT_AGV57; 
            if (NEXT_AGV57) INTERM28 = 1; else INTERM28 = 2; 
            if (NEXT_AGV57) Pos_7_1648 = 1; else Pos_7_1648 = 0; 
            if (C_INTER_NEXT_AGV58)
                {
                if (C_4238) INTER_NEXT_AGV58 = TRUE; else INTER_NEXT_AGV58 = FALSE; 
                }
            if (C_INTER_NEXT_AGV58) NEXT_AGV58 = INTER_NEXT_AGV58; else NEXT_AGV58 = CURRENT_AGV58; 
            if (NEXT_AGV58) INTERM29 = 1; else INTERM29 = 2; 
            cod_x[0] = INTERM0;
            cod_x[1] = INTERM1;
            cod_x[2] = INTERM2;
            cod_x[3] = INTERM3;
            cod_x[4] = INTERM4;
            cod_x[5] = INTERM5;
            cod_x[6] = INTERM6;
            cod_x[7] = INTERM7;
            cod_x[8] = INTERM8;
            cod_x[9] = INTERM9;
            cod_x[10] = INTERM10;
            cod_x[11] = INTERM11;
            cod_x[12] = INTERM12;
            cod_x[13] = INTERM13;
            cod_x[14] = INTERM14;
            cod_x[15] = INTERM15;
            cod_x[16] = INTERM16;
            cod_x[17] = INTERM17;
            cod_x[18] = INTERM18;
            cod_x[19] = INTERM19;
            cod_x[20] = INTERM20;
            cod_x[21] = INTERM21;
            cod_x[22] = INTERM22;
            cod_x[23] = INTERM23;
            cod_x[24] = INTERM24;
            cod_x[25] = INTERM25;
            cod_x[26] = INTERM26;
            cod_x[27] = INTERM27;
            cod_x[28] = INTERM28;
            cod_x[29] = INTERM29;
            if (NEXT_AGV58) Pos_8_1649 = 1; else Pos_8_1649 = 0; 
            Pos_AGV5[0] = 1;
            Pos_AGV5[1] = Pos_1_1642;
            Pos_AGV5[2] = Pos_2_1643;
            Pos_AGV5[3] = Pos_3_1644;
            Pos_AGV5[4] = Pos_4_1645;
            Pos_AGV5[5] = Pos_5_1646;
            Pos_AGV5[6] = Pos_6_1647;
            Pos_AGV5[7] = Pos_7_1648;
            Pos_AGV5[8] = Pos_8_1649;
            dessine_chariot_agv5(Pos_AGV5);
            if (C_INTER_NEXT_WST22)
                {
                if (C_3812) INTER_NEXT_WST22 = TRUE; else INTER_NEXT_WST22 = FALSE; 
                }
            if (C_INTER_NEXT_WST22) NEXT_WST22 = INTER_NEXT_WST22; else NEXT_WST22 = CURRENT_WST22; 
            if (NEXT_WST22) Pos_2_1915 = 1; else Pos_2_1915 = 0; 
            if (C_INTER_NEXT_WST23)
                {
                if (CURRENT_WST22) INTER_NEXT_WST23 = TRUE; else INTER_NEXT_WST23 = FALSE; 
                }
            if (C_INTER_NEXT_WST23) NEXT_WST23 = INTER_NEXT_WST23; else NEXT_WST23 = CURRENT_WST23; 
            if (NEXT_WST23) Pos_3_1916 = 1; else Pos_3_1916 = 0; 
            if (C_INTER_NEXT_WST24)
                {
                if (CURRENT_WST23) INTER_NEXT_WST24 = TRUE; else INTER_NEXT_WST24 = FALSE; 
                }
            if (C_INTER_NEXT_WST24) NEXT_WST24 = INTER_NEXT_WST24; else NEXT_WST24 = CURRENT_WST24; 
            if (NEXT_WST24) Pos_4_1917 = 1; else Pos_4_1917 = 0; 
            Pos_WST2[0] = 1;
            Pos_WST2[1] = Pos_1_1914;
            Pos_WST2[2] = Pos_2_1915;
            Pos_WST2[3] = Pos_3_1916;
            Pos_WST2[4] = Pos_4_1917;
            dessine_chariot_wst2(Pos_WST2);
            if (C_INTER_NEXT_WST32)
                {
                if (C_3899) INTER_NEXT_WST32 = TRUE; else INTER_NEXT_WST32 = FALSE; 
                }
            if (C_INTER_NEXT_WST32) NEXT_WST32 = INTER_NEXT_WST32; else NEXT_WST32 = CURRENT_WST32; 
            if (NEXT_WST32) Pos_2_2021 = 1; else Pos_2_2021 = 0; 
            if (C_INTER_NEXT_WST33)
                {
                if (CURRENT_WST32) INTER_NEXT_WST33 = TRUE; else INTER_NEXT_WST33 = FALSE; 
                }
            if (C_INTER_NEXT_WST33) NEXT_WST33 = INTER_NEXT_WST33; else NEXT_WST33 = CURRENT_WST33; 
            if (NEXT_WST33) Pos_3_2022 = 1; else Pos_3_2022 = 0; 
            if (C_INTER_NEXT_WST34)
                {
                if (CURRENT_WST33) INTER_NEXT_WST34 = TRUE; else INTER_NEXT_WST34 = FALSE; 
                }
            if (C_INTER_NEXT_WST34) NEXT_WST34 = INTER_NEXT_WST34; else NEXT_WST34 = CURRENT_WST34; 
            if (NEXT_WST34) Pos_4_2023 = 1; else Pos_4_2023 = 0; 
            Pos_WST3[0] = 1;
            Pos_WST3[1] = Pos_1_2020;
            Pos_WST3[2] = Pos_2_2021;
            Pos_WST3[3] = Pos_3_2022;
            Pos_WST3[4] = Pos_4_2023;
            dessine_chariot_wst3(Pos_WST3);
            if (C_INTER_NEXT_WST54)
                {
                if (C_4040) INTER_NEXT_WST54 = TRUE; else INTER_NEXT_WST54 = FALSE; 
                }
            if (C_INTER_NEXT_WST54) NEXT_WST54 = INTER_NEXT_WST54; else NEXT_WST54 = CURRENT_WST54; 
            if (NEXT_WST54) Pos_4_2202 = 1; else Pos_4_2202 = 0; 
            if (C_INTER_NEXT_WST52)
                {
                if (C_3947) INTER_NEXT_WST52 = TRUE; else INTER_NEXT_WST52 = FALSE; 
                }
            if (C_INTER_NEXT_WST52) NEXT_WST52 = INTER_NEXT_WST52; else NEXT_WST52 = CURRENT_WST52; 
            if (NEXT_WST52) Pos_2_2200 = 1; else Pos_2_2200 = 0; 
            if (C_INTER_NEXT_WST55)
                {
                if (C_4334) INTER_NEXT_WST55 = TRUE; else INTER_NEXT_WST55 = FALSE; 
                }
            if (C_INTER_NEXT_WST55) NEXT_WST55 = INTER_NEXT_WST55; else NEXT_WST55 = CURRENT_WST55; 
            if (NEXT_WST55) Pos_5_2203 = 1; else Pos_5_2203 = 0; 
            if (C_INTER_NEXT_WST56)
                {
                if (CURRENT_WST55) INTER_NEXT_WST56 = TRUE; else INTER_NEXT_WST56 = FALSE; 
                }
            if (C_INTER_NEXT_WST56) NEXT_WST56 = INTER_NEXT_WST56; else NEXT_WST56 = CURRENT_WST56; 
            if (NEXT_WST56) Pos_6_2204 = 1; else Pos_6_2204 = 0; 
            Pos_WST5[0] = 1;
            Pos_WST5[1] = Pos_1_2199;
            Pos_WST5[2] = Pos_2_2200;
            Pos_WST5[3] = Pos_3_2201;
            Pos_WST5[4] = Pos_4_2202;
            Pos_WST5[5] = Pos_5_2203;
            Pos_WST5[6] = Pos_6_2204;
            dessine_chariot_wst5(Pos_WST5);
            }
        IS_cod_u = IS_cod_u+1;if (IS_cod_u==2) IS_cod_u = 0;
        IS_cod_y = IS_cod_y+1;if (IS_cod_y==2) IS_cod_y = 0;
        resolver(cod_cond,cod_x,TS_cod_u[IS_cod_u],TS_cod_y[IS_cod_y],&fin_resolver);
        b = fin_resolver;
        }
    vt_STEP_finalize();
    return TRUE;
}

EXTERN logical vt_STEP_finalize()
{
    CINIT = FALSE;
    if (C__3040)
        {
        OLD_BOUND = NEW_BOUND;
        }
    if (C_NEXTAUTO)
        {
        ZAUTO = NEXTAUTO;
        }
    if (NEXTAUTO)
        {
        ZV = V;
        }
    if (C_Z_S_cod_y)
        {
        if (z_b)
            {
            CURRENT_WST11 = NEXT_WST11;
            CURRENT_WST12 = NEXT_WST12;
            CURRENT_WST13 = NEXT_WST13;
            CURRENT_WST14 = NEXT_WST14;
            CURRENT_WST21 = NEXT_WST21;
            CURRENT_WST22 = NEXT_WST22;
            CURRENT_WST23 = NEXT_WST23;
            CURRENT_WST24 = NEXT_WST24;
            CURRENT_WST31 = NEXT_WST31;
            CURRENT_WST32 = NEXT_WST32;
            CURRENT_WST33 = NEXT_WST33;
            CURRENT_WST34 = NEXT_WST34;
            CURRENT_WST41 = NEXT_WST41;
            CURRENT_WST42 = NEXT_WST42;
            CURRENT_WST51 = NEXT_WST51;
            CURRENT_WST52 = NEXT_WST52;
            CURRENT_WST53 = NEXT_WST53;
            CURRENT_WST54 = NEXT_WST54;
            CURRENT_WST55 = NEXT_WST55;
            CURRENT_WST56 = NEXT_WST56;
            CURRENT_AGV11 = NEXT_AGV11;
            CURRENT_AGV12 = NEXT_AGV12;
            CURRENT_AGV13 = NEXT_AGV13;
            CURRENT_AGV14 = NEXT_AGV14;
            CURRENT_AGV15 = NEXT_AGV15;
            CURRENT_AGV16 = NEXT_AGV16;
            CURRENT_AGV21 = NEXT_AGV21;
            CURRENT_AGV22 = NEXT_AGV22;
            CURRENT_AGV23 = NEXT_AGV23;
            CURRENT_AGV24 = NEXT_AGV24;
            CURRENT_AGV25 = NEXT_AGV25;
            CURRENT_AGV26 = NEXT_AGV26;
            CURRENT_AGV27 = NEXT_AGV27;
            CURRENT_AGV28 = NEXT_AGV28;
            CURRENT_AGV29 = NEXT_AGV29;
            CURRENT_AGV210 = NEXT_AGV210;
            CURRENT_AGV211 = NEXT_AGV211;
            CURRENT_AGV212 = NEXT_AGV212;
            CURRENT_AGV31 = NEXT_AGV31;
            CURRENT_AGV32 = NEXT_AGV32;
            CURRENT_AGV33 = NEXT_AGV33;
            CURRENT_AGV34 = NEXT_AGV34;
            CURRENT_AGV35 = NEXT_AGV35;
            CURRENT_AGV36 = NEXT_AGV36;
            CURRENT_AGV41 = NEXT_AGV41;
            CURRENT_AGV42 = NEXT_AGV42;
            CURRENT_AGV43 = NEXT_AGV43;
            CURRENT_AGV44 = NEXT_AGV44;
            CURRENT_AGV45 = NEXT_AGV45;
            CURRENT_AGV46 = NEXT_AGV46;
            CURRENT_AGV47 = NEXT_AGV47;
            CURRENT_AGV48 = NEXT_AGV48;
            CURRENT_AGV49 = NEXT_AGV49;
            CURRENT_AGV410 = NEXT_AGV410;
            CURRENT_AGV51 = NEXT_AGV51;
            CURRENT_AGV52 = NEXT_AGV52;
            CURRENT_AGV53 = NEXT_AGV53;
            CURRENT_AGV54 = NEXT_AGV54;
            CURRENT_AGV55 = NEXT_AGV55;
            CURRENT_AGV56 = NEXT_AGV56;
            CURRENT_AGV57 = NEXT_AGV57;
            CURRENT_AGV58 = NEXT_AGV58;
            }
        z_b = b;
        IZ_S_cod_u = IZ_S_cod_u+1;if (IZ_S_cod_u==2) IZ_S_cod_u = 0;
        }
    vt_STEP_initialize();
    return TRUE;
}

