
/*
  Generated by Polychrony (INRIA SIGNAL/DC+ compiler) version  V4.15.8
*/

EXTERN int RCHANGE(int );
EXTERN logical RUPDOWN(int );
EXTERN logical RAUTO();
EXTERN logical RSTOP();
EXTERN logical RTICK();
EXTERN void RESET_PANEL(logical );
EXTERN void WSTOP(logical );
EXTERN void GET_PACE_RHYTHM(int *,int *);
EXTERN void WIWRITE(int ,int );
EXTERN void dessine_chariot_agv1(int [7]);
EXTERN void dessine_chariot_agv2(int [13]);
EXTERN void dessine_chariot_agv3(int [7]);
EXTERN void dessine_chariot_agv4(int [11]);
EXTERN void dessine_chariot_agv5(int [9]);
EXTERN void dessine_chariot_wst1(int [5]);
EXTERN void dessine_chariot_wst2(int [5]);
EXTERN void dessine_chariot_wst3(int [5]);
EXTERN void dessine_chariot_wst4(int [3]);
EXTERN void dessine_chariot_wst5(int [7]);
EXTERN void resolver(int [1],int [30],int [10],int [1],logical *);

EXTERN logical r_vt_HE(logical *HE);

