
/*
  Generated by Polychrony (INRIA SIGNAL/DC+ compiler) version  V4.15.8
*/
#include "vt_types.h"
#include "vt_externals.h"
FILE
    *frHE;

EXTERN void vt_OpenIO()
{
    frHE = fopen("RHE.dat","rt");
    if (!frHE)
        {
        fprintf(stderr,"Can not open file %s\n","RHE.dat");
        exit(1);
        }
    
}

EXTERN void vt_CloseIO()
{
    fclose(frHE);
}

EXTERN logical r_vt_HE(logical *HE)
{
    if (fscanf(frHE,"%d",HE)==EOF)return FALSE;
    return TRUE;
}

