
/*
  Generated by Polychrony (INRIA SIGNAL/DC+ compiler) version  V4.15.8
*/
/*  =======> global definitions */
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "ansi.h"
#include "pK_GenCodeC_Predef.h"
