
/*
  Generated by Polychrony (INRIA SIGNAL/DC+ compiler) version   V4.15.8 (May 2006)
*/
#include "vt_types.h"
#include "vt_externals.h"
#include "vt_body.h"

/*  ==> parameters and indexes */
static int i, i_1781;
/*  ==> input signals     */
static logical HE;
/*  ==> output signals    */
/*  ==> local signals     */
static logical C_UP_DOWN, C_LIN_EXP;
static int PI_0, NEW_BOUND;
static logical CINIT;
static int DESCR;
static logical C_TICK, C_SW_AUTO, NEXTAUTO, C_STOP;
static int CODE_CHANGE, MAX1, V, NEW_BOUND_1, DELTA, VD, VU, NEW_BOUND_2, VD_329, VU_330, INTERM0, INTERM1, INTERM2, INTERM3, INTERM4, INTERM5, INTERM6, INTERM7
           , INTERM8, INTERM9, INTERM10, INTERM11, INTERM12, INTERM13, INTERM14, INTERM15, INTERM16, INTERM17, INTERM18, INTERM19;
static int cod_cond[1];
static int cod_x[20];
static logical Cat_Room_4, Cat_Room_3, Cat_Room_2, Cat_Room_1, Cat_Room_0, Mouse_Room_4, Mouse_Room_3, Mouse_Room_2, Mouse_Room_1, Mouse_Room_0, DoorState_Cat_6
               , DoorState_Cat_5, DoorState_Cat_4, DoorState_Cat_3, DoorState_Cat_2, DoorState_Cat_1, DoorState_Mouse_6, DoorState_Mouse_5, DoorState_Mouse_4, 
               DoorState_Mouse_3, DoorState_Mouse_2, DoorState_Mouse_1, Mvt_Cat_7, Mvt_Cat_6, Mvt_Cat_5, Mvt_Cat_4, Mvt_Cat_3, Mvt_Cat_2, Mvt_Cat_1, Mvt_Mouse_6
               , Mvt_Mouse_5, Mvt_Mouse_4, Mvt_Mouse_3, Mvt_Mouse_2, Mvt_Mouse_1, Inter_Cat_Room_0, Inter_Cat_Room_1, Inter_Cat_Room_3, Inter_Cat_Room_4, 
               Inter_Cat_Room_2, Inter_Mouse_Room_0, Inter_Mouse_Room_1, Inter_Mouse_Room_2, Inter_Mouse_Room_3, Inter_Mouse_Room_4;
static int Pos_Cat[6], Pos_Mouse[6];
static int Door_Cat[7], Door_Mouse[7];
static int Pos_Cat_0, Pos_Cat_1, Pos_Cat_2, Pos_Cat_3, Pos_Cat_4, Pos_Mouse_0, Pos_Mouse_1, Pos_Mouse_2, Pos_Mouse_3, Pos_Mouse_4, Door_Cat_1, Door_Cat_2, 
           Door_Cat_3, Door_Cat_4, Door_Cat_5, Door_Cat_6, Door_Mouse_1, Door_Mouse_2, Door_Mouse_3, Door_Mouse_4, Door_Mouse_5, Door_Mouse_6, Conflict;
static int S_cod_u[12];
static int S_cod_y[13];
static logical fin_resolver, C_C_STOP, C_, C_2715, C_2723, C__2728, C_2730, C_VD, C_2737, C_2742, C_2745, C_VD_2750, C_2752, C_2757, C_2760, C_OLD_BOUND, 
               C_NEXTAUTO, C_VU, C_NEW_BOUND, C_NEW_BOUND_2802, C_2805, C_VU_2808, C_NEW_BOUND_2814, C_NEW_BOUND_2820, C_fin_resolver, C_2839, C_2842, C_2859, 
               C_2862, C_2865, C_2868, C_2980, C_2985, C_2990, C_2995, C_3000, C_3025, C_3030, C_3035, C_3040, C_3045, C_3050, C_3055, C_3060, C_3065, C_3070, 
               C_3075, C_3080, C_3085, C_3090, C_3095, C_3100, C_3105, C_3110, C_3115, C_3120, C_3125, C_3130, C_3135, C_3140, C_3145, C_3150, C_3155, C_3160, 
               C_3165, C_3170, C_3175, C_3180, C_3185, C_3190, C_3195, C_3200, C_3205, C_3210, C_3215, C_3220, C_3225, C_3230, C_3235, C_3240, C_3245, C_3250, 
               C_3255, C_3260, C_3265, C_3270, C_3351, C_3354, C_3357, C_3363, C_3366, C_Inter_Mouse_Room_0, C_3372, C_3375, C_Inter_Cat_Room_0, 
               C_Inter_Mouse_Room_2, C_Inter_Mouse_Room_1, C_3387, C_3390, C_3393, C_Inter_Cat_Room_2, C_3402, C_Inter_Cat_Room_1, C_3408, C_Inter_Mouse_Room_4,
               C_Inter_Mouse_Room_3, C_3420, C_Inter_Cat_Room_4, C_Inter_Cat_Room_3, C_3544, C_3554, C_3558, C_3561, C_3576, C_3579, C_3593, C_3596, C_3606, 
               C_3610, C_3614, C_3618, C_3622, C_3626, C_3630, C_3634, C_3638, C_3642, C_3646, C_3650, C_3654, C_3658, C_3662, C_3666, C_3670, C_3674, C_3678, 
               C_3682, C_3686, C_3690, C_3694, C_3698, C_3702, C_3706, C_3710, C_3714, C_3718;
static int _I;

EXTERN logical vt_initialize()
{
    CINIT = TRUE;
    DESCR = 0;
    NEXTAUTO = TRUE;
    MAX1 = 0;
    V = 1;
    NEW_BOUND = 1;
    cod_cond[0] = 0;
    cod_x[0] = 0;
    Cat_Room_4 = FALSE;
    Mouse_Room_4 = TRUE;
    Cat_Room_3 = FALSE;
    Mouse_Room_3 = FALSE;
    Cat_Room_2 = TRUE;
    Mouse_Room_2 = FALSE;
    Cat_Room_1 = FALSE;
    Mouse_Room_1 = FALSE;
    Cat_Room_0 = FALSE;
    Mouse_Room_0 = FALSE;
    fin_resolver = TRUE;
    for (i = 0;i<12;i += 1)
        S_cod_u[i] = 0;
    for (i_1781 = 0;i_1781<13;i_1781 += 1)
        S_cod_y[i_1781] = 0;
    DoorState_Cat_6 = FALSE;
    DoorState_Cat_4 = FALSE;
    DoorState_Cat_3 = FALSE;
    DoorState_Cat_2 = FALSE;
    DoorState_Cat_1 = FALSE;
    DoorState_Mouse_6 = FALSE;
    DoorState_Mouse_5 = FALSE;
    DoorState_Mouse_4 = FALSE;
    DoorState_Mouse_3 = FALSE;
    DoorState_Mouse_2 = FALSE;
    vt_STEP_initialize();
    return TRUE;
}

static void vt_STEP_initialize()
{
    C_LIN_EXP = FALSE;
    C__2728 = FALSE;
    C_NEW_BOUND = FALSE;
    C_NEW_BOUND_2814 = FALSE;
    C_2859 = FALSE;
    C_2865 = FALSE;
}

EXTERN logical vt_iterate()
{
    if (!r_vt_HE(&HE)) return FALSE;
    C_TICK = RTICK();
    C_SW_AUTO = RAUTO();
    C_NEXTAUTO = CINIT || C_SW_AUTO;
    if (CINIT)
        {
        GET_PACE_RHYTHM(&DESCR,&PI_0);
        }
    CODE_CHANGE = RCHANGE(DESCR);
    C_ = CODE_CHANGE != 0;
    C_OLD_BOUND = CINIT || C_;
    if (C_)
        {
        C_LIN_EXP = CODE_CHANGE == 2;
        C_2742 = FALSE;
        C_UP_DOWN = RUPDOWN(DESCR);
        C__2728 = !C_LIN_EXP;
        C_2757 = FALSE;
        if (C_LIN_EXP)
            {
            C_VD = !C_UP_DOWN;
            }
        if (C__2728)
            {
            C_VD_2750 = !C_UP_DOWN;
            }
        if (C_LIN_EXP)
            {
            C_2730 = NEW_BOUND >= 16;
            C_2737 = NEW_BOUND > 1;
            C_VU = C_UP_DOWN && C_2737;
            if (C_2730) DELTA = NEW_BOUND / 16; else DELTA = 1; 
            if (C_VD)
                {
                VD = NEW_BOUND + DELTA;
                C_2742 = VD > 0;
                }
            C_2745 = (C_VD ? C_2742 : FALSE);
            C_NEW_BOUND = C_VU || C_2745;
            if (C_VU)
                {
                VU = NEW_BOUND - DELTA;
                }
            if (C_NEW_BOUND)
                {
                if (C_VU) NEW_BOUND_1 = VU; else NEW_BOUND_1 = VD; 
                }
            }
        if (C__2728)
            {
            C_2752 = NEW_BOUND > 1;
            C_VU_2808 = C_UP_DOWN && C_2752;
            if (C_VD_2750)
                {
                VD_329 = NEW_BOUND + NEW_BOUND;
                C_2757 = VD_329 > 0;
                }
            C_2760 = (C_VD_2750 ? C_2757 : FALSE);
            C_NEW_BOUND_2814 = C_VU_2808 || C_2760;
            if (C_VU_2808)
                {
                VU_330 = NEW_BOUND / 2;
                }
            if (C_NEW_BOUND_2814)
                {
                if (C_VU_2808) NEW_BOUND_2 = VU_330; else NEW_BOUND_2 = VD_329; 
                }
            }
        }
    C_NEW_BOUND_2802 = (C_LIN_EXP ? C_NEW_BOUND : FALSE);
    C_2805 = CINIT || C_NEW_BOUND_2802;
    C_NEW_BOUND_2820 = (C__2728 ? C_NEW_BOUND_2814 : FALSE);
    C_2839 = !C_2805 && C_NEW_BOUND_2820;
    C_2842 = !CINIT && C_NEW_BOUND_2802;
    if (C_OLD_BOUND)
        {
        if (CINIT) NEW_BOUND = PI_0; else if (C_NEW_BOUND_2802) NEW_BOUND = NEW_BOUND_1; else if (C_NEW_BOUND_2820) NEW_BOUND = NEW_BOUND_2; else ; 
        WIWRITE(DESCR,NEW_BOUND);
        C_2859 = NEW_BOUND <= 1;
        C_2865 = !(NEW_BOUND <= 1);
        }
    C_2862 = (C_OLD_BOUND ? C_2859 : FALSE);
    C_2868 = (C_OLD_BOUND ? C_2865 : FALSE);
    if (C_NEXTAUTO)
        {
        NEXTAUTO = !NEXTAUTO;
        RESET_PANEL(NEXTAUTO);
        }
    C_C_STOP = !NEXTAUTO;
    if (C_C_STOP)
        {
        C_STOP = RSTOP();
        if (C_STOP)
            {
            WSTOP(TRUE);
            }
        }
    if (NEXTAUTO || C_OLD_BOUND)
        {
        if (C_2862)
            MAX1 = 0;
        else if (C_2868)
            MAX1 = NEW_BOUND - 1;
        }
    if (NEXTAUTO)
        {
        C_2715 = V >= MAX1;
        if (C_2715) V = 0; else V = V + 1; 
        }
    C_2723 = (NEXTAUTO ? (V == 0) : FALSE);
    C_fin_resolver = C_TICK || C_2723;
    if (C_fin_resolver)
        {
        if (fin_resolver)
            {
            cod_cond[0] = 0;
            C_3025 = S_cod_y[0] == 1;
            C_3030 = S_cod_y[0] == -1;
            C_3035 = S_cod_y[1] == 1;
            C_3040 = S_cod_y[1] == -1;
            C_3045 = S_cod_y[2] == 1;
            C_3050 = S_cod_y[2] == -1;
            C_3055 = S_cod_y[3] == 1;
            C_3060 = S_cod_y[3] == -1;
            C_3065 = S_cod_y[4] == 1;
            C_3070 = S_cod_y[4] == -1;
            C_3075 = S_cod_y[5] == 1;
            C_3080 = S_cod_y[5] == -1;
            C_3085 = S_cod_y[6] == 1;
            C_3090 = S_cod_y[6] == -1;
            C_3095 = S_cod_y[7] == 1;
            C_3100 = S_cod_y[7] == -1;
            C_3105 = S_cod_y[8] == 1;
            C_3110 = S_cod_y[8] == -1;
            C_3115 = S_cod_y[9] == 1;
            C_3120 = S_cod_y[9] == -1;
            C_3125 = S_cod_y[10] == 1;
            C_3130 = S_cod_y[10] == -1;
            C_3135 = S_cod_y[11] == 1;
            C_3140 = S_cod_y[11] == -1;
            C_3145 = S_cod_y[12] == 1;
            C_3150 = S_cod_y[12] == -1;
            C_3155 = S_cod_u[0] == 1;
            C_3160 = S_cod_u[0] == -1;
            C_3165 = S_cod_u[1] == 1;
            C_3170 = S_cod_u[1] == -1;
            C_3175 = S_cod_u[2] == 1;
            C_3180 = S_cod_u[2] == -1;
            C_3185 = S_cod_u[3] == 1;
            C_3190 = S_cod_u[3] == -1;
            C_3195 = S_cod_u[4] == 1;
            C_3200 = S_cod_u[4] == -1;
            C_3205 = S_cod_u[5] == 1;
            C_3210 = S_cod_u[5] == -1;
            C_3215 = S_cod_u[6] == 1;
            C_3220 = S_cod_u[6] == -1;
            C_3225 = S_cod_u[7] == 1;
            C_3230 = S_cod_u[7] == -1;
            C_3235 = S_cod_u[8] == 1;
            C_3240 = S_cod_u[8] == -1;
            C_3245 = S_cod_u[9] == 1;
            C_3250 = S_cod_u[9] == -1;
            C_3255 = S_cod_u[10] == 1;
            C_3260 = S_cod_u[10] == -1;
            C_3265 = S_cod_u[11] == 1;
            C_3270 = S_cod_u[11] == -1;
            C_3622 = !C_3025 && C_3030;
            C_3626 = !C_3035 && C_3040;
            C_3630 = !C_3045 && C_3050;
            C_3634 = !C_3055 && C_3060;
            C_3638 = !C_3065 && C_3070;
            C_3642 = !C_3075 && C_3080;
            C_3646 = !C_3085 && C_3090;
            C_3650 = !C_3095 && C_3100;
            C_3654 = !C_3105 && C_3110;
            C_3658 = !C_3115 && C_3120;
            C_3662 = !C_3125 && C_3130;
            C_3666 = !C_3135 && C_3140;
            C_3670 = !C_3145 && C_3150;
            C_3674 = !C_3155 && C_3160;
            C_3678 = !C_3165 && C_3170;
            C_3682 = !C_3175 && C_3180;
            C_3686 = !C_3185 && C_3190;
            C_3690 = !C_3195 && C_3200;
            C_3694 = !C_3205 && C_3210;
            C_3698 = !C_3215 && C_3220;
            C_3702 = !C_3225 && C_3230;
            C_3706 = !C_3235 && C_3240;
            C_3710 = !C_3245 && C_3250;
            C_3714 = !C_3255 && C_3260;
            C_3718 = !C_3265 && C_3270;
            if (C_3025) Mvt_Mouse_1 = TRUE; else if (C_3030) Mvt_Mouse_1 = FALSE; else Mvt_Mouse_1 = FALSE; 
            if (C_3035) Mvt_Mouse_2 = TRUE; else if (C_3040) Mvt_Mouse_2 = FALSE; else Mvt_Mouse_2 = FALSE; 
            C_Inter_Mouse_Room_2 = Mvt_Mouse_1 || Mvt_Mouse_2;
            if (C_3045) Mvt_Mouse_3 = TRUE; else if (C_3050) Mvt_Mouse_3 = FALSE; else Mvt_Mouse_3 = FALSE; 
            C_Inter_Mouse_Room_1 = Mvt_Mouse_3 || Mvt_Mouse_2;
            if (C_3055) Mvt_Mouse_4 = TRUE; else if (C_3060) Mvt_Mouse_4 = FALSE; else Mvt_Mouse_4 = FALSE; 
            if (C_3065) Mvt_Mouse_5 = TRUE; else if (C_3070) Mvt_Mouse_5 = FALSE; else Mvt_Mouse_5 = FALSE; 
            C_Inter_Mouse_Room_4 = Mvt_Mouse_4 || Mvt_Mouse_5;
            if (C_3075) Mvt_Mouse_6 = TRUE; else if (C_3080) Mvt_Mouse_6 = FALSE; else Mvt_Mouse_6 = FALSE; 
            C_3363 = Mvt_Mouse_3 || Mvt_Mouse_6;
            C_3366 = Mvt_Mouse_1 || C_3363;
            C_Inter_Mouse_Room_0 = Mvt_Mouse_4 || C_3366;
            C_Inter_Mouse_Room_3 = Mvt_Mouse_6 || Mvt_Mouse_5;
            C_3593 = !C_3363 && Mvt_Mouse_1;
            C_3596 = !Mvt_Mouse_3 && Mvt_Mouse_6;
            if (C_3085) Mvt_Cat_1 = TRUE; else if (C_3090) Mvt_Cat_1 = FALSE; else Mvt_Cat_1 = FALSE; 
            if (C_3095) Mvt_Cat_2 = TRUE; else if (C_3100) Mvt_Cat_2 = FALSE; else Mvt_Cat_2 = FALSE; 
            if (C_3105) Mvt_Cat_3 = TRUE; else if (C_3110) Mvt_Cat_3 = FALSE; else Mvt_Cat_3 = FALSE; 
            C_Inter_Cat_Room_2 = Mvt_Cat_3 || Mvt_Cat_2;
            if (C_3115) Mvt_Cat_4 = TRUE; else if (C_3120) Mvt_Cat_4 = FALSE; else Mvt_Cat_4 = FALSE; 
            if (C_3125) Mvt_Cat_5 = TRUE; else if (C_3130) Mvt_Cat_5 = FALSE; else Mvt_Cat_5 = FALSE; 
            if (C_3135) Mvt_Cat_6 = TRUE; else if (C_3140) Mvt_Cat_6 = FALSE; else Mvt_Cat_6 = FALSE; 
            C_3372 = Mvt_Cat_3 || Mvt_Cat_6;
            C_3375 = Mvt_Cat_1 || C_3372;
            C_Inter_Cat_Room_0 = Mvt_Cat_4 || C_3375;
            C_Inter_Cat_Room_4 = Mvt_Cat_6 || Mvt_Cat_5;
            C_3576 = !C_3372 && Mvt_Cat_1;
            C_3579 = !Mvt_Cat_3 && Mvt_Cat_6;
            if (C_3145) Mvt_Cat_7 = TRUE; else if (C_3150) Mvt_Cat_7 = FALSE; else Mvt_Cat_7 = FALSE; 
            C_3387 = Mvt_Cat_7 && Cat_Room_3;
            C_3390 = C_3387 || Mvt_Cat_1;
            C_3393 = Mvt_Cat_2 || C_3390;
            C_3402 = Mvt_Cat_7 && Cat_Room_1;
            C_Inter_Cat_Room_1 = C_3402 || C_3393;
            C_3408 = C_3402 || Mvt_Cat_4;
            C_3420 = Mvt_Cat_5 || C_3408;
            C_Inter_Cat_Room_3 = C_3420 || C_3387;
            C_3544 = !C_3408 && Mvt_Cat_5;
            C_3554 = !Mvt_Cat_4 && C_3402;
            C_3558 = !C_3390 && Mvt_Cat_2;
            C_3561 = !Mvt_Cat_1 && C_3387;
            if (C_3155) DoorState_Cat_1 = TRUE; else if (C_3160) DoorState_Cat_1 = FALSE; else DoorState_Cat_1 = FALSE; 
            if (DoorState_Cat_1) Door_Cat_1 = 1; else Door_Cat_1 = 0; 
            if (DoorState_Cat_1) INTERM10 = 1; else INTERM10 = 2; 
            if (C_3165) DoorState_Cat_2 = TRUE; else if (C_3170) DoorState_Cat_2 = FALSE; else DoorState_Cat_2 = FALSE; 
            if (DoorState_Cat_2) Door_Cat_2 = 1; else Door_Cat_2 = 0; 
            if (DoorState_Cat_2) INTERM11 = 1; else INTERM11 = 2; 
            if (C_3175) DoorState_Cat_3 = TRUE; else if (C_3180) DoorState_Cat_3 = FALSE; else DoorState_Cat_3 = FALSE; 
            if (DoorState_Cat_3) Door_Cat_3 = 1; else Door_Cat_3 = 0; 
            if (DoorState_Cat_3) INTERM12 = 1; else INTERM12 = 2; 
            if (C_3185) DoorState_Cat_4 = TRUE; else if (C_3190) DoorState_Cat_4 = FALSE; else DoorState_Cat_4 = FALSE; 
            if (DoorState_Cat_4) Door_Cat_4 = 1; else Door_Cat_4 = 0; 
            if (DoorState_Cat_4) INTERM13 = 1; else INTERM13 = 2; 
            if (C_3195) DoorState_Cat_5 = TRUE; else if (C_3200) DoorState_Cat_5 = FALSE; else DoorState_Cat_5 = FALSE; 
            if (DoorState_Cat_5) Door_Cat_5 = 1; else Door_Cat_5 = 0; 
            if (C_3205) DoorState_Cat_6 = TRUE; else if (C_3210) DoorState_Cat_6 = FALSE; else DoorState_Cat_6 = FALSE; 
            if (DoorState_Cat_6) Door_Cat_6 = 1; else Door_Cat_6 = 0; 
            Door_Cat[0] = 1;
            Door_Cat[1] = Door_Cat_1;
            Door_Cat[2] = Door_Cat_2;
            Door_Cat[3] = Door_Cat_3;
            Door_Cat[4] = Door_Cat_4;
            Door_Cat[5] = Door_Cat_5;
            Door_Cat[6] = Door_Cat_6;
            Draw_Door_Cat(Door_Cat);
            if (DoorState_Cat_6) INTERM14 = 1; else INTERM14 = 2; 
            if (C_3215) DoorState_Mouse_1 = TRUE; else if (C_3220) DoorState_Mouse_1 = FALSE; else DoorState_Mouse_1 = FALSE; 
            if (DoorState_Mouse_1) Door_Mouse_1 = 1; else Door_Mouse_1 = 0; 
            if (C_3225) DoorState_Mouse_2 = TRUE; else if (C_3230) DoorState_Mouse_2 = FALSE; else DoorState_Mouse_2 = FALSE; 
            if (DoorState_Mouse_2) Door_Mouse_2 = 1; else Door_Mouse_2 = 0; 
            if (DoorState_Mouse_2) INTERM15 = 1; else INTERM15 = 2; 
            if (C_3235) DoorState_Mouse_3 = TRUE; else if (C_3240) DoorState_Mouse_3 = FALSE; else DoorState_Mouse_3 = FALSE; 
            if (DoorState_Mouse_3) Door_Mouse_3 = 1; else Door_Mouse_3 = 0; 
            if (DoorState_Mouse_3) INTERM16 = 1; else INTERM16 = 2; 
            if (C_3245) DoorState_Mouse_4 = TRUE; else if (C_3250) DoorState_Mouse_4 = FALSE; else DoorState_Mouse_4 = FALSE; 
            if (DoorState_Mouse_4) Door_Mouse_4 = 1; else Door_Mouse_4 = 0; 
            if (DoorState_Mouse_4) INTERM17 = 1; else INTERM17 = 2; 
            if (C_3255) DoorState_Mouse_5 = TRUE; else if (C_3260) DoorState_Mouse_5 = FALSE; else DoorState_Mouse_5 = FALSE; 
            if (DoorState_Mouse_5) Door_Mouse_5 = 1; else Door_Mouse_5 = 0; 
            if (DoorState_Mouse_5) INTERM18 = 1; else INTERM18 = 2; 
            if (C_3265) DoorState_Mouse_6 = TRUE; else if (C_3270) DoorState_Mouse_6 = FALSE; else DoorState_Mouse_6 = FALSE; 
            if (DoorState_Mouse_6) Door_Mouse_6 = 1; else Door_Mouse_6 = 0; 
            Door_Mouse[0] = 1;
            Door_Mouse[1] = Door_Mouse_1;
            Door_Mouse[2] = Door_Mouse_2;
            Door_Mouse[3] = Door_Mouse_3;
            Door_Mouse[4] = Door_Mouse_4;
            Door_Mouse[5] = Door_Mouse_5;
            Door_Mouse[6] = Door_Mouse_6;
            Draw_Door_Mouse(Door_Mouse);
            if (DoorState_Mouse_6) INTERM19 = 1; else INTERM19 = 2; 
            if (C_Inter_Mouse_Room_0)
                {
                if (Mvt_Mouse_3) Inter_Mouse_Room_0 = TRUE; else if (Mvt_Mouse_6) Inter_Mouse_Room_0 = TRUE; else if (Mvt_Mouse_1) Inter_Mouse_Room_0 = FALSE; 
                else Inter_Mouse_Room_0 = FALSE; 
                }
            if (C_Inter_Mouse_Room_0) Mouse_Room_0 = Inter_Mouse_Room_0; else ; 
            if (Mouse_Room_0) INTERM9 = 1; else INTERM9 = 2; 
            if (Mouse_Room_0) Pos_Mouse_0 = 1; else Pos_Mouse_0 = 0; 
            if (C_Inter_Cat_Room_0)
                {
                if (Mvt_Cat_3) Inter_Cat_Room_0 = TRUE; else if (Mvt_Cat_6) Inter_Cat_Room_0 = TRUE; else if (Mvt_Cat_1) Inter_Cat_Room_0 = FALSE; else 
                Inter_Cat_Room_0 = FALSE; 
                }
            if (C_Inter_Cat_Room_0) Cat_Room_0 = Inter_Cat_Room_0; else ; 
            C_2980 = Cat_Room_0 && Mouse_Room_0;
            if (Cat_Room_0) INTERM8 = 1; else INTERM8 = 2; 
            if (Cat_Room_0) Pos_Cat_0 = 1; else Pos_Cat_0 = 0; 
            if (C_Inter_Mouse_Room_2)
                {
                if (Mvt_Mouse_1) Inter_Mouse_Room_2 = TRUE; else Inter_Mouse_Room_2 = FALSE; 
                }
            if (C_Inter_Mouse_Room_2) Mouse_Room_2 = Inter_Mouse_Room_2; else ; 
            if (Mouse_Room_2) INTERM5 = 1; else INTERM5 = 2; 
            if (Mouse_Room_2) Pos_Mouse_2 = 1; else Pos_Mouse_2 = 0; 
            if (C_Inter_Mouse_Room_1)
                {
                if (Mvt_Mouse_2) Inter_Mouse_Room_1 = TRUE; else Inter_Mouse_Room_1 = FALSE; 
                }
            if (C_Inter_Mouse_Room_1) Mouse_Room_1 = Inter_Mouse_Room_1; else ; 
            if (Mouse_Room_1) INTERM7 = 1; else INTERM7 = 2; 
            if (Mouse_Room_1) Pos_Mouse_1 = 1; else Pos_Mouse_1 = 0; 
            if (C_Inter_Cat_Room_2)
                {
                if (Mvt_Cat_2) Inter_Cat_Room_2 = TRUE; else Inter_Cat_Room_2 = FALSE; 
                }
            if (C_Inter_Cat_Room_2) Cat_Room_2 = Inter_Cat_Room_2; else ; 
            C_2990 = Cat_Room_2 && Mouse_Room_2;
            if (Cat_Room_2) INTERM4 = 1; else INTERM4 = 2; 
            if (Cat_Room_2) Pos_Cat_2 = 1; else Pos_Cat_2 = 0; 
            if (C_Inter_Cat_Room_1)
                {
                if (Mvt_Cat_1) Inter_Cat_Room_1 = TRUE; else if (C_3387) Inter_Cat_Room_1 = TRUE; else if (Mvt_Cat_2) Inter_Cat_Room_1 = FALSE; else 
                Inter_Cat_Room_1 = FALSE; 
                }
            if (C_Inter_Cat_Room_1) Cat_Room_1 = Inter_Cat_Room_1; else ; 
            C_2985 = Cat_Room_1 && Mouse_Room_1;
            C_3351 = C_2980 || C_2985;
            C_3354 = C_3351 || C_2990;
            C_3606 = !C_2980 && C_2985;
            C_3610 = !C_3351 && C_2990;
            if (Cat_Room_1) INTERM6 = 1; else INTERM6 = 2; 
            if (Cat_Room_1) Pos_Cat_1 = 1; else Pos_Cat_1 = 0; 
            if (C_Inter_Mouse_Room_4)
                {
                if (Mvt_Mouse_4) Inter_Mouse_Room_4 = TRUE; else Inter_Mouse_Room_4 = FALSE; 
                }
            if (C_Inter_Mouse_Room_4) Mouse_Room_4 = Inter_Mouse_Room_4; else ; 
            if (Mouse_Room_4) INTERM1 = 1; else INTERM1 = 2; 
            if (Mouse_Room_4) Pos_Mouse_4 = 1; else Pos_Mouse_4 = 0; 
            if (C_Inter_Mouse_Room_3)
                {
                if (Mvt_Mouse_5) Inter_Mouse_Room_3 = TRUE; else Inter_Mouse_Room_3 = FALSE; 
                }
            if (C_Inter_Mouse_Room_3) Mouse_Room_3 = Inter_Mouse_Room_3; else ; 
            if (Mouse_Room_3) INTERM3 = 1; else INTERM3 = 2; 
            if (Mouse_Room_3) Pos_Mouse_3 = 1; else Pos_Mouse_3 = 0; 
            Pos_Mouse[0] = 1;
            Pos_Mouse[1] = Pos_Mouse_0;
            Pos_Mouse[2] = Pos_Mouse_1;
            Pos_Mouse[3] = Pos_Mouse_2;
            Pos_Mouse[4] = Pos_Mouse_3;
            Pos_Mouse[5] = Pos_Mouse_4;
            Draw_Mouse(Pos_Mouse);
            if (C_Inter_Cat_Room_4)
                {
                if (Mvt_Cat_5) Inter_Cat_Room_4 = TRUE; else Inter_Cat_Room_4 = FALSE; 
                }
            if (C_Inter_Cat_Room_4) Cat_Room_4 = Inter_Cat_Room_4; else ; 
            C_3000 = Cat_Room_4 && Mouse_Room_4;
            if (Cat_Room_4) INTERM0 = 1; else INTERM0 = 2; 
            if (Cat_Room_4) Pos_Cat_4 = 1; else Pos_Cat_4 = 0; 
            if (C_Inter_Cat_Room_3)
                {
                if (Mvt_Cat_4) Inter_Cat_Room_3 = TRUE; else if (C_3402) Inter_Cat_Room_3 = TRUE; else if (Mvt_Cat_5) Inter_Cat_Room_3 = FALSE; else 
                Inter_Cat_Room_3 = FALSE; 
                }
            if (C_Inter_Cat_Room_3) Cat_Room_3 = Inter_Cat_Room_3; else ; 
            C_2995 = Cat_Room_3 && Mouse_Room_3;
            C_3357 = C_3354 || C_2995;
            C_3614 = !C_3354 && C_2995;
            C_3618 = !C_3357 && C_3000;
            if (Cat_Room_3) INTERM2 = 1; else INTERM2 = 2; 
            cod_x[0] = INTERM0;
            cod_x[1] = INTERM1;
            cod_x[2] = INTERM2;
            cod_x[3] = INTERM3;
            cod_x[4] = INTERM4;
            cod_x[5] = INTERM5;
            cod_x[6] = INTERM6;
            cod_x[7] = INTERM7;
            cod_x[8] = INTERM8;
            cod_x[9] = INTERM9;
            cod_x[10] = INTERM10;
            cod_x[11] = INTERM11;
            cod_x[12] = INTERM12;
            cod_x[13] = INTERM13;
            cod_x[14] = INTERM14;
            cod_x[15] = INTERM15;
            cod_x[16] = INTERM16;
            cod_x[17] = INTERM17;
            cod_x[18] = INTERM18;
            cod_x[19] = INTERM19;
            if (Cat_Room_3) Pos_Cat_3 = 1; else Pos_Cat_3 = 0; 
            Pos_Cat[0] = 1;
            Pos_Cat[1] = Pos_Cat_0;
            Pos_Cat[2] = Pos_Cat_1;
            Pos_Cat[3] = Pos_Cat_2;
            Pos_Cat[4] = Pos_Cat_3;
            Pos_Cat[5] = Pos_Cat_4;
            Draw_Cat(Pos_Cat);
            if (C_2980) Conflict = 1; else if (C_2985) Conflict = 1; else if (C_2990) Conflict = 1; else if (C_2995) Conflict = 1; else if (C_3000) Conflict = 1
            ; else Conflict = 0; 
            Draw_Conflict(Conflict);
            }
        resolver(cod_cond,cod_x,S_cod_u,S_cod_y,&fin_resolver);
        }
    vt_STEP_finalize();
    return TRUE;
}

EXTERN logical vt_STEP_finalize()
{
    CINIT = FALSE;
    vt_STEP_initialize();
    return TRUE;
}

