
/*
  Generated by Polychrony (INRIA SIGNAL/DC+ compiler) version   V4.15.8 (May 2006)
*/
#include "vt_types.h"
#include "vt_externals.h"
#include "vt_body.h"
EXTERN void vt_OpenIO();
EXTERN void vt_CloseIO();

EXTERN int main()
{
    logical code;
    vt_OpenIO();
    code = vt_initialize();
    while(code)code = vt_iterate();
    vt_CloseIO();
}

