
/*
  Generated by Polychrony (INRIA SIGNAL/DC+ compiler) version  V4.15.8 (May 2006) 
*/
EXTERN logical vt_initialize();
static void vt_STEP_initialize();
EXTERN logical vt_STEP_finalize();
EXTERN logical vt_iterate();
