
/*
  Generated by Polychrony (INRIA SIGNAL/DC+ compiler) version  V4.15.8 (May 2006) 
*/
#include "vt_types.h"
#include "vt_externals.h"
#include "vt_body.h"

/*  ==> parameters and indexes */
static int i, i_843;
/*  ==> input signals     */
static logical HE;
/*  ==> output signals    */
/*  ==> local signals     */
static logical C_UP_DOWN, C_LIN_EXP;
static int PI_0, NEW_BOUND;
static logical CINIT;
static int DESCR;
static logical C_TICK, C_SW_AUTO, NEXTAUTO, C_STOP;
static int CODE_CHANGE, MAX1, V, NEW_BOUND_1, DELTA, VD, VU, NEW_BOUND_2, VD_330, VU_331, INTERM0, INTERM1, INTERM2, INTERM3;
static int cod_cond[1];
static int cod_x[4];
static logical Mult, Incr, CC, New_B1, New_B2, New_B3, New_B4, C1, C2, C3, C4, C1a, C2a, C3a, C4a, CCa, CCa_483, Cout1, Cout1_539;
static int S_cod_u[2];
static int S_cod_y[1];
static logical fin_resolver, C_C_STOP, C_, C_1105, C_1113, C__1118, C_1120, C_VD, C_1127, C_1132, C_1135, C_VD_1140, C_1142, C_1147, C_1150, C_OLD_BOUND, 
               C_NEXTAUTO, C_VU, C_NEW_BOUND, C_NEW_BOUND_1192, C_1195, C_VU_1198, C_NEW_BOUND_1204, C_NEW_BOUND_1210, C_fin_resolver, C_1229, C_1232, C_1249, 
               C_1252, C_1255, C_1258, C_1292, C_1297, C_1302, C_1307, C_C4, C_1331, C_1335, C_1339;
static int _I;

EXTERN logical vt_initialize()
{
    CINIT = TRUE;
    DESCR = 0;
    NEXTAUTO = TRUE;
    MAX1 = 0;
    V = 1;
    NEW_BOUND = 1;
    cod_cond[0] = 0;
    cod_x[0] = 0;
    New_B1 = FALSE;
    New_B2 = FALSE;
    New_B3 = FALSE;
    New_B4 = FALSE;
    fin_resolver = TRUE;
    for (i = 0;i<2;i += 1)
        S_cod_u[i] = 0;
    vt_STEP_initialize();
    return TRUE;
}

static void vt_STEP_initialize()
{
    C_LIN_EXP = FALSE;
    C__1118 = FALSE;
    C_NEW_BOUND = FALSE;
    C_NEW_BOUND_1204 = FALSE;
    C_1249 = FALSE;
    C_1255 = FALSE;
}

EXTERN logical vt_iterate()
{
    if (!r_vt_HE(&HE)) return FALSE;
    C_TICK = RTICK();
    C_SW_AUTO = RAUTO();
    C_NEXTAUTO = CINIT || C_SW_AUTO;
    if (CINIT)
        {
        GET_PACE_RHYTHM(&DESCR,&PI_0);
        }
    CODE_CHANGE = RCHANGE(DESCR);
    C_ = CODE_CHANGE != 0;
    C_OLD_BOUND = CINIT || C_;
    if (C_)
        {
        C_LIN_EXP = CODE_CHANGE == 2;
        C_1132 = FALSE;
        C_UP_DOWN = RUPDOWN(DESCR);
        C__1118 = !C_LIN_EXP;
        C_1147 = FALSE;
        if (C_LIN_EXP)
            {
            C_VD = !C_UP_DOWN;
            }
        if (C__1118)
            {
            C_VD_1140 = !C_UP_DOWN;
            }
        if (C_LIN_EXP)
            {
            C_1120 = NEW_BOUND >= 16;
            C_1127 = NEW_BOUND > 1;
            C_VU = C_UP_DOWN && C_1127;
            if (C_1120) DELTA = NEW_BOUND / 16; else DELTA = 1; 
            if (C_VD)
                {
                VD = NEW_BOUND + DELTA;
                C_1132 = VD > 0;
                }
            C_1135 = (C_VD ? C_1132 : FALSE);
            C_NEW_BOUND = C_VU || C_1135;
            if (C_VU)
                {
                VU = NEW_BOUND - DELTA;
                }
            if (C_NEW_BOUND)
                {
                if (C_VU) NEW_BOUND_1 = VU; else NEW_BOUND_1 = VD; 
                }
            }
        if (C__1118)
            {
            C_1142 = NEW_BOUND > 1;
            C_VU_1198 = C_UP_DOWN && C_1142;
            if (C_VD_1140)
                {
                VD_330 = NEW_BOUND + NEW_BOUND;
                C_1147 = VD_330 > 0;
                }
            C_1150 = (C_VD_1140 ? C_1147 : FALSE);
            C_NEW_BOUND_1204 = C_VU_1198 || C_1150;
            if (C_VU_1198)
                {
                VU_331 = NEW_BOUND / 2;
                }
            if (C_NEW_BOUND_1204)
                {
                if (C_VU_1198) NEW_BOUND_2 = VU_331; else NEW_BOUND_2 = VD_330; 
                }
            }
        }
    C_NEW_BOUND_1192 = (C_LIN_EXP ? C_NEW_BOUND : FALSE);
    C_1195 = CINIT || C_NEW_BOUND_1192;
    C_NEW_BOUND_1210 = (C__1118 ? C_NEW_BOUND_1204 : FALSE);
    C_1229 = !C_1195 && C_NEW_BOUND_1210;
    C_1232 = !CINIT && C_NEW_BOUND_1192;
    if (C_OLD_BOUND)
        {
        if (CINIT) NEW_BOUND = PI_0; else if (C_NEW_BOUND_1192) NEW_BOUND = NEW_BOUND_1; else if (C_NEW_BOUND_1210) NEW_BOUND = NEW_BOUND_2; else ; 
        WIWRITE(DESCR,NEW_BOUND);
        C_1249 = NEW_BOUND <= 1;
        C_1255 = !(NEW_BOUND <= 1);
        }
    C_1252 = (C_OLD_BOUND ? C_1249 : FALSE);
    C_1258 = (C_OLD_BOUND ? C_1255 : FALSE);
    if (C_NEXTAUTO)
        {
        NEXTAUTO = !NEXTAUTO;
        RESET_PANEL(NEXTAUTO);
        }
    C_C_STOP = !NEXTAUTO;
    if (C_C_STOP)
        {
        C_STOP = RSTOP();
        if (C_STOP)
            {
            WSTOP(TRUE);
            }
        }
    if (NEXTAUTO || C_OLD_BOUND)
        {
        if (C_1252)
            MAX1 = 0;
        else if (C_1258)
            MAX1 = NEW_BOUND - 1;
        }
    if (NEXTAUTO)
        {
        C_1105 = V >= MAX1;
        if (C_1105) V = 0; else V = V + 1; 
        }
    C_1113 = (NEXTAUTO ? (V == 0) : FALSE);
    C_fin_resolver = C_TICK || C_1113;
    if (C_fin_resolver)
        {
        if (fin_resolver)
            {
            cod_cond[0] = 0;
            C_1292 = S_cod_u[0] == 1;
            C_1297 = S_cod_u[0] == -1;
            C_1302 = S_cod_u[1] == 1;
            C_1307 = S_cod_u[1] == -1;
            C_1335 = !C_1292 && C_1297;
            C_1339 = !C_1302 && C_1307;
            if (C_1292) Incr = TRUE; else if (C_1297) Incr = FALSE; else Incr = FALSE; 
            if (Incr) C1a = !New_B1; else C1a = New_B1; 
            Cout1 = New_B1 && !C1a;
            if (Cout1) C2a = !New_B2; else C2a = New_B2; 
            CCa_483 = New_B2 && !C2a;
            if (CCa_483) C3a = !New_B3; else C3a = New_B3; 
            Cout1_539 = New_B3 && !C3a;
            if (Cout1_539) C4a = !New_B4; else C4a = New_B4; 
            CCa = New_B4 && !C4a;
            if (C_1302) Mult = TRUE; else if (C_1307) Mult = FALSE; else Mult = FALSE; 
            C_C4 = Incr || Mult;
            C_1331 = !Incr && Mult;
            if (Incr) CC = CCa; else if (Mult) CC = New_B4; else CC = FALSE; 
            if (C_C4)
                {
                if (Incr) C1 = C1a; else C1 = FALSE; 
                if (Incr) C2 = C2a; else C2 = New_B1; 
                if (Incr) C3 = C3a; else C3 = New_B2; 
                if (Incr) C4 = C4a; else C4 = New_B3; 
                }
            if (C_C4) New_B1 = C1; else ; 
            if (C_C4) New_B2 = C2; else ; 
            if (C_C4) New_B3 = C3; else ; 
            if (C_C4) New_B4 = C4; else ; 
            Draw(CC,New_B1,New_B2,New_B3,New_B4);
            if (New_B1) INTERM0 = 1; else INTERM0 = 2; 
            if (New_B2) INTERM1 = 1; else INTERM1 = 2; 
            if (New_B3) INTERM2 = 1; else INTERM2 = 2; 
            if (New_B4) INTERM3 = 1; else INTERM3 = 2; 
            cod_x[0] = INTERM0;
            cod_x[1] = INTERM1;
            cod_x[2] = INTERM2;
            cod_x[3] = INTERM3;
            }
        resolver(cod_cond,cod_x,S_cod_u,S_cod_y,&fin_resolver);
        }
    vt_STEP_finalize();
    return TRUE;
}

EXTERN logical vt_STEP_finalize()
{
    CINIT = FALSE;
    vt_STEP_initialize();
    return TRUE;
}

