
/*
  Generated by Polychrony (INRIA SIGNAL/DC+ compiler) version  V4.15.8 (May 2006) 
*/

EXTERN void WIWRITE(int ,int );
EXTERN void GET_PACE_RHYTHM(int *,int *);
EXTERN logical RTICK();
EXTERN logical RAUTO();
EXTERN logical RSTOP();
EXTERN int RCHANGE(int );
EXTERN logical RUPDOWN(int );
EXTERN void WSTOP(logical );
EXTERN void RESET_PANEL(logical );
EXTERN void Draw(logical ,logical ,logical ,logical ,logical );
EXTERN void resolver(int [1],int [4],int [2],int [1],logical *);

EXTERN logical r_vt_HE(logical *HE);

