/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LiaisonBody */

#ifndef _Included_LiaisonBody
#define _Included_LiaisonBody
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LiaisonBody
 * Method:    connexionBody
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_LiaisonBody_connexionBody
  (JNIEnv *, jobject);

/*
 * Class:     LiaisonBody
 * Method:    n_vt_initialise
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_LiaisonBody_n_1vt_1initialise
  (JNIEnv *, jobject);

/*
 * Class:     LiaisonBody
 * Method:    n_vt_iterate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_LiaisonBody_n_1vt_1iterate
  (JNIEnv *, jobject);

/*
 * Class:     LiaisonBody
 * Method:    n_set_variable
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_LiaisonBody_n_1set_1variable
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
